// Quadlet keys with short help (from podman-systemd.unit(5)). `multi` keys
// may appear several times. `form` marks the keys the form view shows; all
// other keys stay untouched in the file and are edited in the text view.

import { msg, type MsgKey } from './i18n'
import type { QuadletType } from './quadlets'

export interface KeyDoc {
  help: string
  multi?: boolean
  form?: boolean
  placeholder?: string
  options?: string[]
}

/** A key doc whose help text follows the viewer's language (read when rendered, not at import). */
export const k = (key: MsgKey, rest: Omit<KeyDoc, 'help'> = {}): KeyDoc => ({
  ...rest,
  get help() {
    return msg(key)
  },
})

const C: Record<string, KeyDoc> = {
  Image: k('quadletHelp_container_Image', {
    form: true,
    placeholder: 'docker.io/library/nginx:latest',
  }),
  ContainerName: k('quadletHelp_container_ContainerName', { form: true }),
  PublishPort: k('quadletHelp_container_PublishPort', { multi: true, form: true, placeholder: '8080:80' }),
  Volume: k('quadletHelp_container_Volume', {
    multi: true,
    form: true,
    placeholder: '/srv/app:/data:Z',
  }),
  Environment: k('quadletHelp_container_Environment', { multi: true, form: true, placeholder: 'TZ=Europe/Berlin' }),
  EnvironmentFile: k('quadletHelp_container_EnvironmentFile', { multi: true, form: true }),
  Network: k('quadletHelp_container_Network', { multi: true, form: true, placeholder: 'app.network' }),
  AutoUpdate: k('quadletHelp_container_AutoUpdate', { form: true, options: ['', 'registry', 'local'] }),
  Label: k('quadletHelp_container_Label', { multi: true, form: true }),
  Exec: k('quadletHelp_container_Exec', { form: true }),
  Entrypoint: k('quadletHelp_container_Entrypoint'),
  User: k('quadletHelp_container_User', { form: true }),
  Group: k('quadletHelp_container_Group'),
  UserNS: k('quadletHelp_container_UserNS'),
  HealthCmd: k('quadletHelp_container_HealthCmd', { form: true }),
  HealthInterval: k('quadletHelp_container_HealthInterval', { form: true }),
  HealthOnFailure: k('quadletHelp_container_HealthOnFailure', { options: ['', 'none', 'kill', 'restart', 'stop'] }),
  HealthRetries: k('quadletHelp_container_HealthRetries'),
  HealthStartPeriod: k('quadletHelp_container_HealthStartPeriod'),
  HealthTimeout: k('quadletHelp_container_HealthTimeout'),
  Pod: k('quadletHelp_container_Pod', { form: true }),
  AddDevice: k('quadletHelp_container_AddDevice', { multi: true, form: true }),
  AddCapability: k('quadletHelp_container_AddCapability', { multi: true }),
  DropCapability: k('quadletHelp_container_DropCapability', { multi: true }),
  HostName: k('quadletHelp_container_HostName'),
  IP: k('quadletHelp_container_IP'),
  IP6: k('quadletHelp_container_IP6'),
  Memory: k('quadletHelp_container_Memory'),
  PodmanArgs: k('quadletHelp_container_PodmanArgs', { multi: true }),
  ReadOnly: k('quadletHelp_container_ReadOnly'),
  Secret: k('quadletHelp_container_Secret', { multi: true }),
  Timezone: k('quadletHelp_container_Timezone', { form: true }),
  Tmpfs: k('quadletHelp_container_Tmpfs', { multi: true }),
  WorkingDir: k('quadletHelp_container_WorkingDir'),
  Annotation: k('quadletHelp_container_Annotation', { multi: true }),
  ContainersConfModule: k('quadletHelp_container_ContainersConfModule', { multi: true }),
  DNS: k('quadletHelp_container_DNS', { multi: true }),
  DNSOption: k('quadletHelp_container_DNSOption', { multi: true }),
  DNSSearch: k('quadletHelp_container_DNSSearch', { multi: true }),
  ExposeHostPort: k('quadletHelp_container_ExposeHostPort', { multi: true }),
  GIDMap: k('quadletHelp_container_GIDMap', { multi: true }),
  UIDMap: k('quadletHelp_container_UIDMap', { multi: true }),
  SubGIDMap: k('quadletHelp_container_SubGIDMap'),
  SubUIDMap: k('quadletHelp_container_SubUIDMap'),
  GlobalArgs: k('quadletHelp_container_GlobalArgs', { multi: true }),
  LogDriver: k('quadletHelp_container_LogDriver'),
  LogOpt: k('quadletHelp_container_LogOpt', { multi: true }),
  Mask: k('quadletHelp_container_Mask'),
  Unmask: k('quadletHelp_container_Unmask'),
  Mount: k('quadletHelp_container_Mount', { multi: true }),
  NetworkAlias: k('quadletHelp_container_NetworkAlias', { multi: true }),
  NoNewPrivileges: k('quadletHelp_container_NoNewPrivileges'),
  Notify: k('quadletHelp_container_Notify'),
  PidsLimit: k('quadletHelp_container_PidsLimit'),
  Pull: k('quadletHelp_container_Pull'),
  ReadOnlyTmpfs: k('quadletHelp_container_ReadOnlyTmpfs'),
  RunInit: k('quadletHelp_container_RunInit'),
  SeccompProfile: k('quadletHelp_container_SeccompProfile'),
  SecurityLabelDisable: k('quadletHelp_container_SecurityLabelDisable'),
  SecurityLabelFileType: k('quadletHelp_container_SecurityLabelFileType'),
  SecurityLabelLevel: k('quadletHelp_container_SecurityLabelLevel'),
  SecurityLabelNested: k('quadletHelp_container_SecurityLabelNested'),
  SecurityLabelType: k('quadletHelp_container_SecurityLabelType'),
  ShmSize: k('quadletHelp_container_ShmSize'),
  StartWithPod: k('quadletHelp_container_StartWithPod'),
  StopSignal: k('quadletHelp_container_StopSignal'),
  StopTimeout: k('quadletHelp_container_StopTimeout'),
  Sysctl: k('quadletHelp_container_Sysctl', { multi: true }),
  Ulimit: k('quadletHelp_container_Ulimit', { multi: true }),
  CgroupsMode: k('quadletHelp_container_CgroupsMode'),
  EnvironmentHost: k('quadletHelp_container_EnvironmentHost'),
  HealthLogDestination: k('quadletHelp_container_HealthLogDestination'),
  HealthMaxLogCount: k('quadletHelp_container_HealthMaxLogCount'),
  HealthMaxLogSize: k('quadletHelp_container_HealthMaxLogSize'),
  HealthStartupCmd: k('quadletHelp_container_HealthStartupCmd'),
  HealthStartupInterval: k('quadletHelp_container_HealthStartupInterval'),
  HealthStartupRetries: k('quadletHelp_container_HealthStartupRetries'),
  HealthStartupSuccess: k('quadletHelp_container_HealthStartupSuccess'),
  HealthStartupTimeout: k('quadletHelp_container_HealthStartupTimeout'),
  ReloadCmd: k('quadletHelp_container_ReloadCmd'),
  ReloadSignal: k('quadletHelp_container_ReloadSignal'),
  Retry: k('quadletHelp_container_Retry'),
  RetryDelay: k('quadletHelp_container_RetryDelay'),
  Rootfs: k('quadletHelp_container_Rootfs'),
  ServiceName: k('quadletHelp_container_ServiceName'),
  DefaultDependencies: k('quadletHelp_container_DefaultDependencies'),
}

const POD: Record<string, KeyDoc> = {
  PodName: k('quadletHelp_pod_PodName', { form: true }),
  PublishPort: C.PublishPort!,
  Network: C.Network!,
  Volume: C.Volume!,
  NetworkAlias: C.NetworkAlias!,
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  DNS: C.DNS!,
  DNSOption: C.DNSOption!,
  DNSSearch: C.DNSSearch!,
  AddHost: k('quadletHelp_pod_AddHost', { multi: true }),
  IP: C.IP!,
  IP6: C.IP6!,
  UserNS: C.UserNS!,
  UIDMap: C.UIDMap!,
  GIDMap: C.GIDMap!,
  SubUIDMap: C.SubUIDMap!,
  SubGIDMap: C.SubGIDMap!,
  ServiceName: C.ServiceName!,
  ShmSize: C.ShmSize!,
  HostName: C.HostName!,
  Label: C.Label!,
  ExitPolicy: k('quadletHelp_pod_ExitPolicy'),
  StopTimeout: C.StopTimeout!,
}

const NET: Record<string, KeyDoc> = {
  NetworkName: k('quadletHelp_network_NetworkName', { form: true }),
  Subnet: k('quadletHelp_network_Subnet', { multi: true, form: true }),
  Gateway: k('quadletHelp_network_Gateway', { multi: true, form: true }),
  IPRange: k('quadletHelp_network_IPRange', { multi: true }),
  IPv6: k('quadletHelp_network_IPv6', { form: true, options: ['', 'true', 'false'] }),
  Internal: k('quadletHelp_network_Internal', { form: true, options: ['', 'true', 'false'] }),
  Driver: k('quadletHelp_network_Driver', { form: true }),
  DNS: C.DNS!,
  DisableDNS: k('quadletHelp_network_DisableDNS'),
  IPAMDriver: k('quadletHelp_network_IPAMDriver'),
  InterfaceName: k('quadletHelp_network_InterfaceName'),
  Label: C.Label!,
  Options: k('quadletHelp_network_Options', { multi: true }),
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  NetworkDeleteOnStop: k('quadletHelp_network_NetworkDeleteOnStop'),
  ServiceName: C.ServiceName!,
}

const VOL: Record<string, KeyDoc> = {
  VolumeName: k('quadletHelp_volume_VolumeName', { form: true }),
  Driver: k('quadletHelp_volume_Driver', { form: true }),
  Device: k('quadletHelp_volume_Device', { form: true }),
  Type: k('quadletHelp_volume_Type', { form: true }),
  Options: k('quadletHelp_volume_Options', { form: true }),
  Copy: k('quadletHelp_volume_Copy'),
  Group: k('quadletHelp_volume_Group'),
  User: k('quadletHelp_volume_User'),
  Image: k('quadletHelp_volume_Image'),
  Label: C.Label!,
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  ServiceName: C.ServiceName!,
}

const KUBE: Record<string, KeyDoc> = {
  Yaml: k('quadletHelp_kube_Yaml', { form: true }),
  Network: C.Network!,
  PublishPort: C.PublishPort!,
  AutoUpdate: C.AutoUpdate!,
  ConfigMap: k('quadletHelp_kube_ConfigMap', { multi: true }),
  ExitCodePropagation: k('quadletHelp_kube_ExitCodePropagation'),
  KubeDownForce: k('quadletHelp_kube_KubeDownForce'),
  LogDriver: C.LogDriver!,
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  SetWorkingDirectory: k('quadletHelp_kube_SetWorkingDirectory'),
  UserNS: C.UserNS!,
  ServiceName: C.ServiceName!,
}

const IMG: Record<string, KeyDoc> = {
  Image: k('quadletHelp_image_Image', { form: true }),
  ImageTag: k('quadletHelp_image_ImageTag'),
  AllTags: k('quadletHelp_image_AllTags'),
  Arch: k('quadletHelp_image_Arch'),
  AuthFile: k('quadletHelp_image_AuthFile'),
  CertDir: k('quadletHelp_image_CertDir'),
  Creds: k('quadletHelp_image_Creds'),
  DecryptionKey: k('quadletHelp_image_DecryptionKey'),
  OS: k('quadletHelp_image_OS'),
  TLSVerify: k('quadletHelp_image_TLSVerify'),
  Variant: k('quadletHelp_image_Variant'),
  Retry: C.Retry!,
  RetryDelay: C.RetryDelay!,
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  ServiceName: C.ServiceName!,
}

const BUILD: Record<string, KeyDoc> = {
  ImageTag: k('quadletHelp_build_ImageTag', { form: true }),
  File: k('quadletHelp_build_File', { form: true }),
  SetWorkingDirectory: k('quadletHelp_build_SetWorkingDirectory', { form: true }),
  Annotation: C.Annotation!,
  Arch: IMG.Arch!,
  AuthFile: IMG.AuthFile!,
  DNS: C.DNS!,
  DNSOption: C.DNSOption!,
  DNSSearch: C.DNSSearch!,
  Environment: C.Environment!,
  ForceRM: k('quadletHelp_build_ForceRM'),
  GroupAdd: k('quadletHelp_build_GroupAdd', { multi: true }),
  Label: C.Label!,
  Network: C.Network!,
  Pull: C.Pull!,
  Secret: C.Secret!,
  Target: k('quadletHelp_build_Target'),
  TLSVerify: IMG.TLSVerify!,
  Variant: IMG.Variant!,
  Volume: C.Volume!,
  BuildArg: k('quadletHelp_build_BuildArg', { multi: true }),
  IgnoreFile: k('quadletHelp_build_IgnoreFile'),
  Retry: C.Retry!,
  RetryDelay: C.RetryDelay!,
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  ServiceName: C.ServiceName!,
}

export const QUADLET_SECTION: Record<QuadletType, string> = {
  container: 'Container',
  pod: 'Pod',
  network: 'Network',
  volume: 'Volume',
  kube: 'Kube',
  image: 'Image',
  build: 'Build',
}

export const QUADLET_KEYS: Record<string, Record<string, KeyDoc>> = {
  Container: C,
  Pod: POD,
  Network: NET,
  Volume: VOL,
  Kube: KUBE,
  Image: IMG,
  Build: BUILD,
}

/** systemd sections shown in the form (keys are passed through unchanged). */
export const SYSTEMD_KEYS: Record<string, Record<string, KeyDoc>> = {
  Unit: {
    Description: k('quadletHelp_systemd_Description', { form: true }),
    After: k('quadletHelp_systemd_After', { multi: true, form: true }),
    Requires: k('quadletHelp_systemd_Requires', { multi: true, form: true }),
    Wants: k('quadletHelp_systemd_Wants', { multi: true }),
  },
  Service: {
    Restart: k('quadletHelp_systemd_Restart', { form: true, options: ['', 'always', 'on-failure', 'no'] }),
    TimeoutStartSec: k('quadletHelp_systemd_TimeoutStartSec', { form: true }),
  },
  Install: {
    WantedBy: k('quadletHelp_systemd_WantedBy', { multi: true, form: true, options: ['', 'multi-user.target', 'default.target'] }),
  },
}
