// Quadlet keys with short help (from podman-systemd.unit(5)). `multi` keys
// may appear several times. `form` marks the keys the form view shows; all
// other keys stay untouched in the file and are edited in the text view.

import type { QuadletType } from './quadlets'

export interface KeyDoc {
  help: string
  multi?: boolean
  form?: boolean
  placeholder?: string
  options?: string[]
}

const C: Record<string, KeyDoc> = {
  Image: { help: 'Image, am besten voll qualifiziert (docker.io/…), sonst funktioniert AutoUpdate=registry nicht.', form: true, placeholder: 'docker.io/library/nginx:latest' },
  ContainerName: { help: 'Name des Containers (Standard: systemd-<Dateiname>).', form: true },
  PublishPort: { help: 'Port veröffentlichen: [IP:]Host-Port:Container-Port[/udp].', multi: true, form: true, placeholder: '8080:80' },
  Volume: { help: 'Volume oder Verzeichnis einbinden: Quelle:Ziel[:Optionen]; .volume-Dateien per Name.volume.', multi: true, form: true, placeholder: '/srv/app:/data:Z' },
  Environment: { help: 'Umgebungsvariable KEY=VALUE.', multi: true, form: true, placeholder: 'TZ=Europe/Berlin' },
  EnvironmentFile: { help: 'Datei mit Umgebungsvariablen.', multi: true, form: true },
  Network: { help: 'Netzwerk: host, none, ein Podman-Netz oder eine .network-Datei (name.network).', multi: true, form: true, placeholder: 'app.network' },
  AutoUpdate: { help: 'registry: podman auto-update zieht neue Images; local: nur lokal gebaute.', form: true, options: ['', 'registry', 'local'] },
  Label: { help: 'Label KEY=VALUE (z. B. quadeck.url=https://…, quadeck.group=Medien).', multi: true, form: true },
  Exec: { help: 'Argumente für den Befehl im Image (ersetzt CMD).', form: true },
  Entrypoint: { help: 'Entrypoint überschreiben.' },
  User: { help: 'Benutzer im Container (UID oder Name).', form: true },
  Group: { help: 'Gruppe im Container.' },
  UserNS: { help: 'User-Namespace, z. B. keep-id oder auto.' },
  HealthCmd: { help: 'Befehl für den Healthcheck.', form: true },
  HealthInterval: { help: 'Abstand der Healthchecks, z. B. 30s.', form: true },
  HealthOnFailure: { help: 'Aktion bei ungesund: none, kill, restart, stop.', options: ['', 'none', 'kill', 'restart', 'stop'] },
  HealthRetries: { help: 'Fehlversuche bis „unhealthy“.' },
  HealthStartPeriod: { help: 'Schonzeit nach dem Start.' },
  HealthTimeout: { help: 'Timeout eines Healthchecks.' },
  Pod: { help: 'Pod (.pod-Datei), in dem der Container läuft.', form: true },
  AddDevice: { help: 'Gerät durchreichen, z. B. /dev/dri.', multi: true, form: true },
  AddCapability: { help: 'Linux-Capability hinzufügen.', multi: true },
  DropCapability: { help: 'Linux-Capability entfernen.', multi: true },
  HostName: { help: 'Hostname im Container.' },
  IP: { help: 'Feste IPv4-Adresse im Netz.' },
  IP6: { help: 'Feste IPv6-Adresse im Netz.' },
  Memory: { help: 'Speicherlimit (z. B. 2G).' },
  PodmanArgs: { help: 'Zusätzliche Argumente für podman run.', multi: true },
  ReadOnly: { help: 'Root-Dateisystem nur lesbar.' },
  Secret: { help: 'Podman-Secret einbinden.', multi: true },
  Timezone: { help: 'Zeitzone, z. B. local oder Europe/Berlin.', form: true },
  Tmpfs: { help: 'tmpfs einbinden.', multi: true },
  WorkingDir: { help: 'Arbeitsverzeichnis im Container.' },
  Annotation: { help: 'OCI-Annotation.', multi: true },
  ContainersConfModule: { help: 'containers.conf-Modul laden.', multi: true },
  DNS: { help: 'DNS-Server.', multi: true },
  DNSOption: { help: 'DNS-Option.', multi: true },
  DNSSearch: { help: 'DNS-Suchdomäne.', multi: true },
  ExposeHostPort: { help: 'Port exponieren (ohne Veröffentlichen).', multi: true },
  GIDMap: { help: 'GID-Mapping.', multi: true },
  UIDMap: { help: 'UID-Mapping.', multi: true },
  SubGIDMap: { help: 'subgid-Mapping.' },
  SubUIDMap: { help: 'subuid-Mapping.' },
  GlobalArgs: { help: 'Globale podman-Argumente.', multi: true },
  LogDriver: { help: 'Log-Treiber (journald, k8s-file, none).' },
  LogOpt: { help: 'Log-Option.', multi: true },
  Mask: { help: 'Pfade maskieren.' },
  Unmask: { help: 'Pfade freigeben.' },
  Mount: { help: 'Mount im --mount-Format.', multi: true },
  NetworkAlias: { help: 'Alias im Netzwerk.', multi: true },
  NoNewPrivileges: { help: 'Keine neuen Rechte im Container.' },
  Notify: { help: 'sd_notify durchreichen (true/healthy).' },
  PidsLimit: { help: 'Prozesslimit.' },
  Pull: { help: 'Pull-Richtlinie: always, missing, never, newer.' },
  ReadOnlyTmpfs: { help: 'tmpfs bei ReadOnly.' },
  RunInit: { help: 'Init-Prozess im Container.' },
  SeccompProfile: { help: 'Seccomp-Profil.' },
  SecurityLabelDisable: { help: 'SELinux-Labels abschalten.' },
  SecurityLabelFileType: { help: 'SELinux-Dateityp.' },
  SecurityLabelLevel: { help: 'SELinux-Level.' },
  SecurityLabelNested: { help: 'Verschachteltes SELinux.' },
  SecurityLabelType: { help: 'SELinux-Typ.' },
  ShmSize: { help: 'Größe von /dev/shm.' },
  StartWithPod: { help: 'Mit dem Pod starten.' },
  StopSignal: { help: 'Signal zum Stoppen.' },
  StopTimeout: { help: 'Wartezeit beim Stoppen.' },
  Sysctl: { help: 'sysctl setzen.', multi: true },
  Ulimit: { help: 'ulimit setzen.', multi: true },
  CgroupsMode: { help: 'cgroups-Modus.' },
  EnvironmentHost: { help: 'Umgebung des Hosts übernehmen.' },
  HealthLogDestination: { help: 'Ziel des Health-Logs.' },
  HealthMaxLogCount: { help: 'Anzahl Health-Logs.' },
  HealthMaxLogSize: { help: 'Größe Health-Log.' },
  HealthStartupCmd: { help: 'Startup-Healthcheck.' },
  HealthStartupInterval: { help: 'Abstand Startup-Healthcheck.' },
  HealthStartupRetries: { help: 'Versuche Startup-Healthcheck.' },
  HealthStartupSuccess: { help: 'Erfolge Startup-Healthcheck.' },
  HealthStartupTimeout: { help: 'Timeout Startup-Healthcheck.' },
  ReloadCmd: { help: 'Befehl bei systemctl reload.' },
  ReloadSignal: { help: 'Signal bei systemctl reload.' },
  Retry: { help: 'Pull-Wiederholungen.' },
  RetryDelay: { help: 'Pause zwischen Pull-Versuchen.' },
  Rootfs: { help: 'Root-Dateisystem statt Image.' },
  ServiceName: { help: 'Name der systemd-Unit überschreiben.' },
  DefaultDependencies: { help: 'Standard-Abhängigkeiten.' },
}

const POD: Record<string, KeyDoc> = {
  PodName: { help: 'Name des Pods.', form: true },
  PublishPort: C.PublishPort!,
  Network: C.Network!,
  Volume: C.Volume!,
  NetworkAlias: C.NetworkAlias!,
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  DNS: C.DNS!,
  DNSOption: C.DNSOption!,
  DNSSearch: C.DNSSearch!,
  AddHost: { help: 'Eintrag in /etc/hosts.', multi: true },
  IP: C.IP!,
  IP6: C.IP6!,
  UserNS: C.UserNS!,
  UIDMap: C.UIDMap!,
  GIDMap: C.GIDMap!,
  SubUIDMap: C.SubUIDMap!,
  SubGIDMap: C.SubGIDMap!,
  ServiceName: C.ServiceName!,
  ShmSize: C.ShmSize!,
  HostName: C.HostName!,
  Label: C.Label!,
  ExitPolicy: { help: 'Verhalten, wenn alle Container beendet sind.' },
  StopTimeout: C.StopTimeout!,
}

const NET: Record<string, KeyDoc> = {
  NetworkName: { help: 'Name des Podman-Netzes (Standard: systemd-<Dateiname>).', form: true },
  Subnet: { help: 'Subnetz, z. B. 10.89.0.0/24.', multi: true, form: true },
  Gateway: { help: 'Gateway-Adresse.', multi: true, form: true },
  IPRange: { help: 'Bereich für vergebene Adressen.', multi: true },
  IPv6: { help: 'IPv6 aktivieren.', form: true, options: ['', 'true', 'false'] },
  Internal: { help: 'Kein Zugriff nach außen.', form: true, options: ['', 'true', 'false'] },
  Driver: { help: 'Treiber: bridge, macvlan, ipvlan.', form: true },
  DNS: C.DNS!,
  DisableDNS: { help: 'DNS im Netz abschalten.' },
  IPAMDriver: { help: 'IPAM-Treiber.' },
  InterfaceName: { help: 'Name der Schnittstelle.' },
  Label: C.Label!,
  Options: { help: 'Treiberoptionen.', multi: true },
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  NetworkDeleteOnStop: { help: 'Netz beim Stoppen löschen.' },
  ServiceName: C.ServiceName!,
}

const VOL: Record<string, KeyDoc> = {
  VolumeName: { help: 'Name des Volumes (Standard: systemd-<Dateiname>).', form: true },
  Driver: { help: 'Treiber, z. B. local oder image.', form: true },
  Device: { help: 'Gerät oder Quelle (bei Type=nfs u. a.).', form: true },
  Type: { help: 'Dateisystemtyp für mount.', form: true },
  Options: { help: 'Mount-Optionen.', form: true },
  Copy: { help: 'Inhalt des Images ins Volume kopieren.' },
  Group: { help: 'Gruppe des Volumes.' },
  User: { help: 'Besitzer des Volumes.' },
  Image: { help: 'Image für Driver=image.' },
  Label: C.Label!,
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  ServiceName: C.ServiceName!,
}

const KUBE: Record<string, KeyDoc> = {
  Yaml: { help: 'Pfad zur Kubernetes-YAML.', form: true },
  Network: C.Network!,
  PublishPort: C.PublishPort!,
  AutoUpdate: C.AutoUpdate!,
  ConfigMap: { help: 'ConfigMap-Datei.', multi: true },
  ExitCodePropagation: { help: 'Exit-Code-Weitergabe.' },
  KubeDownForce: { help: 'Volumes beim Stoppen entfernen.' },
  LogDriver: C.LogDriver!,
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  SetWorkingDirectory: { help: 'Arbeitsverzeichnis setzen.' },
  UserNS: C.UserNS!,
  ServiceName: C.ServiceName!,
}

const IMG: Record<string, KeyDoc> = {
  Image: { help: 'Zu ziehendes Image.', form: true },
  ImageTag: { help: 'Name, unter dem das Image referenziert wird.' },
  AllTags: { help: 'Alle Tags ziehen.' },
  Arch: { help: 'Architektur.' },
  AuthFile: { help: 'Auth-Datei.' },
  CertDir: { help: 'Zertifikatsverzeichnis.' },
  Creds: { help: 'Zugangsdaten.' },
  DecryptionKey: { help: 'Schlüssel zum Entschlüsseln.' },
  OS: { help: 'Betriebssystem.' },
  TLSVerify: { help: 'TLS prüfen.' },
  Variant: { help: 'Variante.' },
  Retry: C.Retry!,
  RetryDelay: C.RetryDelay!,
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  ServiceName: C.ServiceName!,
}

const BUILD: Record<string, KeyDoc> = {
  ImageTag: { help: 'Tag des gebauten Images.', form: true },
  File: { help: 'Containerfile.', form: true },
  SetWorkingDirectory: { help: 'Build-Kontext.', form: true },
  Annotation: C.Annotation!,
  Arch: IMG.Arch!,
  AuthFile: IMG.AuthFile!,
  DNS: C.DNS!,
  DNSOption: C.DNSOption!,
  DNSSearch: C.DNSSearch!,
  Environment: C.Environment!,
  ForceRM: { help: 'Zwischencontainer entfernen.' },
  GroupAdd: { help: 'Zusätzliche Gruppen.', multi: true },
  Label: C.Label!,
  Network: C.Network!,
  Pull: C.Pull!,
  Secret: C.Secret!,
  Target: { help: 'Build-Stufe.' },
  TLSVerify: IMG.TLSVerify!,
  Variant: IMG.Variant!,
  Volume: C.Volume!,
  BuildArg: { help: 'Build-Argument.', multi: true },
  IgnoreFile: { help: 'Ignore-Datei.' },
  Retry: C.Retry!,
  RetryDelay: C.RetryDelay!,
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  ServiceName: C.ServiceName!,
}

export const QUADLET_SECTION: Record<QuadletType, string> = {
  container: 'Container',
  pod: 'Pod',
  network: 'Network',
  volume: 'Volume',
  kube: 'Kube',
  image: 'Image',
  build: 'Build',
}

export const QUADLET_KEYS: Record<string, Record<string, KeyDoc>> = {
  Container: C,
  Pod: POD,
  Network: NET,
  Volume: VOL,
  Kube: KUBE,
  Image: IMG,
  Build: BUILD,
}

/** systemd sections shown in the form (keys are passed through unchanged). */
export const SYSTEMD_KEYS: Record<string, Record<string, KeyDoc>> = {
  Unit: {
    Description: { help: 'Beschreibung der Unit.', form: true },
    After: { help: 'Nach diesen Units starten (z. B. network-online.target).', multi: true, form: true },
    Requires: { help: 'Diese Units mitstarten; fällt eine aus, stoppt diese auch.', multi: true, form: true },
    Wants: { help: 'Diese Units mitstarten (weiche Abhängigkeit).', multi: true },
  },
  Service: {
    Restart: { help: 'Neustart-Richtlinie (always, on-failure, no).', form: true, options: ['', 'always', 'on-failure', 'no'] },
    TimeoutStartSec: { help: 'Wartezeit beim Start (Image-Pull!), z. B. 900.', form: true },
  },
  Install: {
    WantedBy: { help: 'Beim Booten starten: multi-user.target (oder default.target).', multi: true, form: true, options: ['', 'multi-user.target', 'default.target'] },
  },
}
