// Quadlet keys with short help (from podman-systemd.unit(5)). `multi` keys
// may appear several times. `form` marks the keys the form view shows; all
// other keys stay untouched in the file and are edited in the text view.

import { msg, type Message } from './i18n'
import { m } from '~/paraglide/messages'
import type { QuadletType } from './quadlets'

export interface KeyDoc {
  help: string
  multi?: boolean
  form?: boolean
  placeholder?: string
  options?: string[]
}

/** A key doc whose help text follows the viewer's language (read when rendered, not at import). */
export const k = (key: Message, rest: Omit<KeyDoc, 'help'> = {}): KeyDoc => ({
  ...rest,
  get help() {
    return msg(key)
  },
})

const C: Record<string, KeyDoc> = {
  Image: k(m.quadletHelp_container_Image, {
    form: true,
    placeholder: 'docker.io/library/nginx:latest',
  }),
  ContainerName: k(m.quadletHelp_container_ContainerName, { form: true }),
  PublishPort: k(m.quadletHelp_container_PublishPort, { multi: true, form: true, placeholder: '8080:80' }),
  Volume: k(m.quadletHelp_container_Volume, {
    multi: true,
    form: true,
    placeholder: '/srv/app:/data:Z',
  }),
  Environment: k(m.quadletHelp_container_Environment, { multi: true, form: true, placeholder: 'TZ=Europe/Berlin' }),
  EnvironmentFile: k(m.quadletHelp_container_EnvironmentFile, { multi: true, form: true }),
  Network: k(m.quadletHelp_container_Network, { multi: true, form: true, placeholder: 'app.network' }),
  AutoUpdate: k(m.quadletHelp_container_AutoUpdate, { form: true, options: ['', 'registry', 'local'] }),
  Label: k(m.quadletHelp_container_Label, { multi: true, form: true }),
  Exec: k(m.quadletHelp_container_Exec, { form: true }),
  Entrypoint: k(m.quadletHelp_container_Entrypoint),
  User: k(m.quadletHelp_container_User, { form: true }),
  Group: k(m.quadletHelp_container_Group),
  UserNS: k(m.quadletHelp_container_UserNS),
  HealthCmd: k(m.quadletHelp_container_HealthCmd, { form: true }),
  HealthInterval: k(m.quadletHelp_container_HealthInterval, { form: true }),
  HealthOnFailure: k(m.quadletHelp_container_HealthOnFailure, { options: ['', 'none', 'kill', 'restart', 'stop'] }),
  HealthRetries: k(m.quadletHelp_container_HealthRetries),
  HealthStartPeriod: k(m.quadletHelp_container_HealthStartPeriod),
  HealthTimeout: k(m.quadletHelp_container_HealthTimeout),
  Pod: k(m.quadletHelp_container_Pod, { form: true }),
  AddDevice: k(m.quadletHelp_container_AddDevice, { multi: true, form: true }),
  AddCapability: k(m.quadletHelp_container_AddCapability, { multi: true }),
  DropCapability: k(m.quadletHelp_container_DropCapability, { multi: true }),
  HostName: k(m.quadletHelp_container_HostName),
  IP: k(m.quadletHelp_container_IP),
  IP6: k(m.quadletHelp_container_IP6),
  Memory: k(m.quadletHelp_container_Memory),
  PodmanArgs: k(m.quadletHelp_container_PodmanArgs, { multi: true }),
  ReadOnly: k(m.quadletHelp_container_ReadOnly),
  Secret: k(m.quadletHelp_container_Secret, { multi: true, form: true, placeholder: 'db-password,type=env,target=DB_PASSWORD' }),
  Timezone: k(m.quadletHelp_container_Timezone, { form: true }),
  Tmpfs: k(m.quadletHelp_container_Tmpfs, { multi: true }),
  WorkingDir: k(m.quadletHelp_container_WorkingDir),
  Annotation: k(m.quadletHelp_container_Annotation, { multi: true }),
  ContainersConfModule: k(m.quadletHelp_container_ContainersConfModule, { multi: true }),
  DNS: k(m.quadletHelp_container_DNS, { multi: true }),
  DNSOption: k(m.quadletHelp_container_DNSOption, { multi: true }),
  DNSSearch: k(m.quadletHelp_container_DNSSearch, { multi: true }),
  ExposeHostPort: k(m.quadletHelp_container_ExposeHostPort, { multi: true }),
  GIDMap: k(m.quadletHelp_container_GIDMap, { multi: true }),
  UIDMap: k(m.quadletHelp_container_UIDMap, { multi: true }),
  SubGIDMap: k(m.quadletHelp_container_SubGIDMap),
  SubUIDMap: k(m.quadletHelp_container_SubUIDMap),
  GlobalArgs: k(m.quadletHelp_container_GlobalArgs, { multi: true }),
  LogDriver: k(m.quadletHelp_container_LogDriver),
  LogOpt: k(m.quadletHelp_container_LogOpt, { multi: true }),
  Mask: k(m.quadletHelp_container_Mask),
  Unmask: k(m.quadletHelp_container_Unmask),
  Mount: k(m.quadletHelp_container_Mount, { multi: true }),
  NetworkAlias: k(m.quadletHelp_container_NetworkAlias, { multi: true }),
  NoNewPrivileges: k(m.quadletHelp_container_NoNewPrivileges),
  Notify: k(m.quadletHelp_container_Notify),
  PidsLimit: k(m.quadletHelp_container_PidsLimit),
  Pull: k(m.quadletHelp_container_Pull),
  ReadOnlyTmpfs: k(m.quadletHelp_container_ReadOnlyTmpfs),
  RunInit: k(m.quadletHelp_container_RunInit),
  SeccompProfile: k(m.quadletHelp_container_SeccompProfile),
  SecurityLabelDisable: k(m.quadletHelp_container_SecurityLabelDisable),
  SecurityLabelFileType: k(m.quadletHelp_container_SecurityLabelFileType),
  SecurityLabelLevel: k(m.quadletHelp_container_SecurityLabelLevel),
  SecurityLabelNested: k(m.quadletHelp_container_SecurityLabelNested),
  SecurityLabelType: k(m.quadletHelp_container_SecurityLabelType),
  ShmSize: k(m.quadletHelp_container_ShmSize),
  StartWithPod: k(m.quadletHelp_container_StartWithPod),
  StopSignal: k(m.quadletHelp_container_StopSignal),
  StopTimeout: k(m.quadletHelp_container_StopTimeout),
  Sysctl: k(m.quadletHelp_container_Sysctl, { multi: true }),
  Ulimit: k(m.quadletHelp_container_Ulimit, { multi: true }),
  CgroupsMode: k(m.quadletHelp_container_CgroupsMode),
  EnvironmentHost: k(m.quadletHelp_container_EnvironmentHost),
  HealthLogDestination: k(m.quadletHelp_container_HealthLogDestination),
  HealthMaxLogCount: k(m.quadletHelp_container_HealthMaxLogCount),
  HealthMaxLogSize: k(m.quadletHelp_container_HealthMaxLogSize),
  HealthStartupCmd: k(m.quadletHelp_container_HealthStartupCmd),
  HealthStartupInterval: k(m.quadletHelp_container_HealthStartupInterval),
  HealthStartupRetries: k(m.quadletHelp_container_HealthStartupRetries),
  HealthStartupSuccess: k(m.quadletHelp_container_HealthStartupSuccess),
  HealthStartupTimeout: k(m.quadletHelp_container_HealthStartupTimeout),
  ReloadCmd: k(m.quadletHelp_container_ReloadCmd),
  ReloadSignal: k(m.quadletHelp_container_ReloadSignal),
  Retry: k(m.quadletHelp_container_Retry),
  RetryDelay: k(m.quadletHelp_container_RetryDelay),
  Rootfs: k(m.quadletHelp_container_Rootfs),
  ServiceName: k(m.quadletHelp_container_ServiceName),
  DefaultDependencies: k(m.quadletHelp_container_DefaultDependencies),
}

const POD: Record<string, KeyDoc> = {
  PodName: k(m.quadletHelp_pod_PodName, { form: true }),
  PublishPort: C.PublishPort!,
  Network: C.Network!,
  Volume: C.Volume!,
  NetworkAlias: C.NetworkAlias!,
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  DNS: C.DNS!,
  DNSOption: C.DNSOption!,
  DNSSearch: C.DNSSearch!,
  AddHost: k(m.quadletHelp_pod_AddHost, { multi: true }),
  IP: C.IP!,
  IP6: C.IP6!,
  UserNS: C.UserNS!,
  UIDMap: C.UIDMap!,
  GIDMap: C.GIDMap!,
  SubUIDMap: C.SubUIDMap!,
  SubGIDMap: C.SubGIDMap!,
  ServiceName: C.ServiceName!,
  ShmSize: C.ShmSize!,
  HostName: C.HostName!,
  Label: C.Label!,
  ExitPolicy: k(m.quadletHelp_pod_ExitPolicy),
  StopTimeout: C.StopTimeout!,
}

const NET: Record<string, KeyDoc> = {
  NetworkName: k(m.quadletHelp_network_NetworkName, { form: true }),
  Subnet: k(m.quadletHelp_network_Subnet, { multi: true, form: true }),
  Gateway: k(m.quadletHelp_network_Gateway, { multi: true, form: true }),
  IPRange: k(m.quadletHelp_network_IPRange, { multi: true }),
  IPv6: k(m.quadletHelp_network_IPv6, { form: true, options: ['', 'true', 'false'] }),
  Internal: k(m.quadletHelp_network_Internal, { form: true, options: ['', 'true', 'false'] }),
  Driver: k(m.quadletHelp_network_Driver, { form: true }),
  DNS: C.DNS!,
  DisableDNS: k(m.quadletHelp_network_DisableDNS),
  IPAMDriver: k(m.quadletHelp_network_IPAMDriver),
  InterfaceName: k(m.quadletHelp_network_InterfaceName),
  Label: C.Label!,
  Options: k(m.quadletHelp_network_Options, { multi: true }),
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  NetworkDeleteOnStop: k(m.quadletHelp_network_NetworkDeleteOnStop),
  ServiceName: C.ServiceName!,
}

const VOL: Record<string, KeyDoc> = {
  VolumeName: k(m.quadletHelp_volume_VolumeName, { form: true }),
  Driver: k(m.quadletHelp_volume_Driver, { form: true }),
  Device: k(m.quadletHelp_volume_Device, { form: true }),
  Type: k(m.quadletHelp_volume_Type, { form: true }),
  Options: k(m.quadletHelp_volume_Options, { form: true }),
  Copy: k(m.quadletHelp_volume_Copy),
  Group: k(m.quadletHelp_volume_Group),
  User: k(m.quadletHelp_volume_User),
  Image: k(m.quadletHelp_volume_Image),
  Label: C.Label!,
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  ServiceName: C.ServiceName!,
}

const KUBE: Record<string, KeyDoc> = {
  Yaml: k(m.quadletHelp_kube_Yaml, { form: true }),
  Network: C.Network!,
  PublishPort: C.PublishPort!,
  AutoUpdate: C.AutoUpdate!,
  ConfigMap: k(m.quadletHelp_kube_ConfigMap, { multi: true }),
  ExitCodePropagation: k(m.quadletHelp_kube_ExitCodePropagation),
  KubeDownForce: k(m.quadletHelp_kube_KubeDownForce),
  LogDriver: C.LogDriver!,
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  SetWorkingDirectory: k(m.quadletHelp_kube_SetWorkingDirectory),
  UserNS: C.UserNS!,
  ServiceName: C.ServiceName!,
}

const IMG: Record<string, KeyDoc> = {
  Image: k(m.quadletHelp_image_Image, { form: true }),
  ImageTag: k(m.quadletHelp_image_ImageTag),
  AllTags: k(m.quadletHelp_image_AllTags),
  Arch: k(m.quadletHelp_image_Arch),
  AuthFile: k(m.quadletHelp_image_AuthFile),
  CertDir: k(m.quadletHelp_image_CertDir),
  Creds: k(m.quadletHelp_image_Creds),
  DecryptionKey: k(m.quadletHelp_image_DecryptionKey),
  OS: k(m.quadletHelp_image_OS),
  TLSVerify: k(m.quadletHelp_image_TLSVerify),
  Variant: k(m.quadletHelp_image_Variant),
  Retry: C.Retry!,
  RetryDelay: C.RetryDelay!,
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  ServiceName: C.ServiceName!,
}

const BUILD: Record<string, KeyDoc> = {
  ImageTag: k(m.quadletHelp_build_ImageTag, { form: true }),
  File: k(m.quadletHelp_build_File, { form: true }),
  SetWorkingDirectory: k(m.quadletHelp_build_SetWorkingDirectory, { form: true }),
  Annotation: C.Annotation!,
  Arch: IMG.Arch!,
  AuthFile: IMG.AuthFile!,
  DNS: C.DNS!,
  DNSOption: C.DNSOption!,
  DNSSearch: C.DNSSearch!,
  Environment: C.Environment!,
  ForceRM: k(m.quadletHelp_build_ForceRM),
  GroupAdd: k(m.quadletHelp_build_GroupAdd, { multi: true }),
  Label: C.Label!,
  Network: C.Network!,
  Pull: C.Pull!,
  Secret: C.Secret!,
  Target: k(m.quadletHelp_build_Target),
  TLSVerify: IMG.TLSVerify!,
  Variant: IMG.Variant!,
  Volume: C.Volume!,
  BuildArg: k(m.quadletHelp_build_BuildArg, { multi: true }),
  IgnoreFile: k(m.quadletHelp_build_IgnoreFile),
  Retry: C.Retry!,
  RetryDelay: C.RetryDelay!,
  PodmanArgs: C.PodmanArgs!,
  GlobalArgs: C.GlobalArgs!,
  ContainersConfModule: C.ContainersConfModule!,
  ServiceName: C.ServiceName!,
}

export const QUADLET_SECTION: Record<QuadletType, string> = {
  container: 'Container',
  pod: 'Pod',
  network: 'Network',
  volume: 'Volume',
  kube: 'Kube',
  image: 'Image',
  build: 'Build',
}

export const QUADLET_KEYS: Record<string, Record<string, KeyDoc>> = {
  Container: C,
  Pod: POD,
  Network: NET,
  Volume: VOL,
  Kube: KUBE,
  Image: IMG,
  Build: BUILD,
}

/** systemd sections shown in the form (keys are passed through unchanged). */
export const SYSTEMD_KEYS: Record<string, Record<string, KeyDoc>> = {
  Unit: {
    Description: k(m.quadletHelp_systemd_Description, { form: true }),
    After: k(m.quadletHelp_systemd_After, { multi: true, form: true }),
    Requires: k(m.quadletHelp_systemd_Requires, { multi: true, form: true }),
    Wants: k(m.quadletHelp_systemd_Wants, { multi: true }),
  },
  Service: {
    Restart: k(m.quadletHelp_systemd_Restart, { form: true, options: ['', 'always', 'on-failure', 'no'] }),
    TimeoutStartSec: k(m.quadletHelp_systemd_TimeoutStartSec, { form: true }),
  },
  Install: {
    WantedBy: k(m.quadletHelp_systemd_WantedBy, { multi: true, form: true, options: ['', 'multi-user.target', 'default.target'] }),
  },
}
