// Generated by scripts/gen-migrations.ts from ./drizzle. Do not edit.
export const migrations: { tag: string; statements: string[] }[] = [
  {
    "tag": "0000_init",
    "statements": [
      "CREATE TABLE `groups` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text NOT NULL,\n\t`order` integer DEFAULT 0 NOT NULL,\n\t`collapsed` integer DEFAULT false NOT NULL\n);",
      "CREATE UNIQUE INDEX `groups_name_unique` ON `groups` (`name`);",
      "CREATE TABLE `layouts` (\n\t`breakpoint` text NOT NULL,\n\t`widget_id` text NOT NULL,\n\t`x` integer NOT NULL,\n\t`y` integer NOT NULL,\n\t`w` integer NOT NULL,\n\t`h` integer NOT NULL,\n\tPRIMARY KEY(`breakpoint`, `widget_id`)\n);",
      "CREATE TABLE `manual_services` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text NOT NULL,\n\t`url` text NOT NULL,\n\t`icon` text,\n\t`group` text,\n\t`health_check` integer DEFAULT true NOT NULL\n);",
      "CREATE TABLE `metric_samples` (\n\t`ts` integer NOT NULL,\n\t`metric` text NOT NULL,\n\t`value` real NOT NULL\n);",
      "CREATE INDEX `metric_samples_metric_ts` ON `metric_samples` (`metric`,`ts`);",
      "CREATE TABLE `service_overrides` (\n\t`service_key` text PRIMARY KEY NOT NULL,\n\t`name` text,\n\t`icon` text,\n\t`group` text,\n\t`url` text,\n\t`hidden` integer DEFAULT false NOT NULL,\n\t`pinned` integer DEFAULT false NOT NULL\n);",
      "CREATE TABLE `sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`csrf` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`expires_at` integer NOT NULL\n);",
      "CREATE TABLE `settings` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL\n);",
      "CREATE TABLE `widgets` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`type` text NOT NULL,\n\t`config` text DEFAULT '{}' NOT NULL\n);"
    ]
  },
  {
    "tag": "0001_flashy_next_avengers",
    "statements": [
      "DROP INDEX `metric_samples_metric_ts`;",
      "CREATE INDEX `metric_samples_metric_ts_value` ON `metric_samples` (`metric`,`ts`,`value`);"
    ]
  },
  {
    "tag": "0002_freezing_grey_gargoyle",
    "statements": [
      "CREATE TABLE `passkeys` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`public_key` text NOT NULL,\n\t`counter` integer DEFAULT 0 NOT NULL,\n\t`transports` text,\n\t`rp_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`last_used_at` integer\n);"
    ]
  }
]
