// Builds the single binary: vite build, then `bun build --compile` with the
// client assets embedded. Usage: bun scripts/compile.ts [target…]
//   targets: bun-linux-x64-baseline bun-linux-arm64 bun-linux-x64-musl bun-linux-arm64-musl
import { readdirSync, statSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, relative } from 'node:path'
import { $ } from 'bun'
import pkg from '../package.json'

const ALL = ['bun-linux-x64-baseline', 'bun-linux-arm64', 'bun-linux-x64-musl', 'bun-linux-arm64-musl']
const targets = process.argv.slice(2).length ? process.argv.slice(2) : [`bun-linux-${process.arch === 'arm64' ? 'arm64' : 'x64-baseline'}`]
for (const t of targets) if (!ALL.includes(t)) throw new Error(`unknown target ${t}`)

if (!process.env.SKIP_VITE) await $`bun --bun vite build`

const walk = (dir: string): string[] => readdirSync(dir).flatMap((f) => (statSync(join(dir, f)).isDirectory() ? walk(join(dir, f)) : [join(dir, f)]))
const files = walk('dist/client')
mkdirSync('build', { recursive: true })
const lines = [
  '// Generated by scripts/compile.ts. Do not edit.',
  // @simplewebauthn/server → @peculiar/x509 → tsyringe needs Reflect.getMetadata before any of it
  // runs; in the single bundle its own import of the polyfill comes too late.
  "import 'reflect-metadata'",
  "import server from '../dist/server/server.js'",
  "import { main } from '../src/main'",
  ...files.map((f, i) => `import f${i} from '../${f}' with { type: 'file' }`),
  `const assets = new Map<string, string>([${files.map((f, i) => `['/${relative('dist/client', f)}', f${i}]`).join(', ')}])`,
  `await main(process.argv.slice(2), { server, assets, version: ${JSON.stringify(pkg.version)} })`,
]
writeFileSync('build/entry.ts', lines.join('\n') + '\n')

mkdirSync('release', { recursive: true })
for (const target of targets) {
  const out = `release/quadeck-${target.replace(/^bun-/, '')}`
  await $`bun build build/entry.ts --compile --minify --target=${target} --outfile ${out}`
  console.log(`→ ${out}`)
}
