// Embeds drizzle-kit's SQL migrations into a TS module, so the compiled
// binary carries them (there is no migrations folder next to the binary).
import { readFileSync, writeFileSync } from 'node:fs'

const journal = JSON.parse(readFileSync('drizzle/meta/_journal.json', 'utf8')) as { entries: { tag: string }[] }
const migrations = journal.entries.map((e) => ({
  tag: e.tag,
  statements: readFileSync(`drizzle/${e.tag}.sql`, 'utf8').split('--> statement-breakpoint').map((s) => s.trim()).filter(Boolean),
}))
writeFileSync(
  'src/server/db/migrations.gen.ts',
  `// Generated by scripts/gen-migrations.ts from ./drizzle. Do not edit.\nexport const migrations: { tag: string; statements: string[] }[] = ${JSON.stringify(migrations, null, 2)}\n`,
)
console.log(`embedded ${migrations.length} migration(s)`)
