/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppJournalRouteImport } from './routes/_app/journal'
import { Route as AppUnitsRouteImport } from './routes/_app/units'
import { Route as ApiContainersRouteImport } from './routes/api/containers'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiJournalRouteImport } from './routes/api/journal'
import { Route as ApiUnitsRouteImport } from './routes/api/units'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthSetupRouteImport } from './routes/api/auth/setup'
import { Route as ApiFaviconKeyRouteImport } from './routes/api/favicon/$key'
import { Route as ApiIconsSlugRouteImport } from './routes/api/icons/$slug'
import { Route as ApiLayoutIndexRouteImport } from './routes/api/layout/index'
import { Route as ApiLayoutHiddenRouteImport } from './routes/api/layout/hidden'
import { Route as ApiLinksIndexRouteImport } from './routes/api/links/index'
import { Route as ApiLinksIdRouteImport } from './routes/api/links/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppUnitsRoute = AppUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppRoute,
} as any)
const ApiContainersRoute = ApiContainersRouteImport.update({
  id: '/api/containers',
  path: '/api/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJournalRoute = ApiJournalRouteImport.update({
  id: '/api/journal',
  path: '/api/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnitsRoute = ApiUnitsRouteImport.update({
  id: '/api/units',
  path: '/api/units',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSetupRoute = ApiAuthSetupRouteImport.update({
  id: '/api/auth/setup',
  path: '/api/auth/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFaviconKeyRoute = ApiFaviconKeyRouteImport.update({
  id: '/api/favicon/$key',
  path: '/api/favicon/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIconsSlugRoute = ApiIconsSlugRouteImport.update({
  id: '/api/icons/$slug',
  path: '/api/icons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLayoutIndexRoute = ApiLayoutIndexRouteImport.update({
  id: '/api/layout/',
  path: '/api/layout/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLayoutHiddenRoute = ApiLayoutHiddenRouteImport.update({
  id: '/api/layout/hidden',
  path: '/api/layout/hidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinksIndexRoute = ApiLinksIndexRouteImport.update({
  id: '/api/links/',
  path: '/api/links/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinksIdRoute = ApiLinksIdRouteImport.update({
  id: '/api/links/$id',
  path: '/api/links/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/journal': typeof AppJournalRoute
  '/units': typeof AppUnitsRoute
  '/api/containers': typeof ApiContainersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/units': typeof ApiUnitsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/favicon/$key': typeof ApiFaviconKeyRoute
  '/api/icons/$slug': typeof ApiIconsSlugRoute
  '/api/layout/hidden': typeof ApiLayoutHiddenRoute
  '/api/links/$id': typeof ApiLinksIdRoute
  '/api/layout/': typeof ApiLayoutIndexRoute
  '/api/links/': typeof ApiLinksIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/journal': typeof AppJournalRoute
  '/units': typeof AppUnitsRoute
  '/api/containers': typeof ApiContainersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/units': typeof ApiUnitsRoute
  '/': typeof AppIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/favicon/$key': typeof ApiFaviconKeyRoute
  '/api/icons/$slug': typeof ApiIconsSlugRoute
  '/api/layout/hidden': typeof ApiLayoutHiddenRoute
  '/api/links/$id': typeof ApiLinksIdRoute
  '/api/layout': typeof ApiLayoutIndexRoute
  '/api/links': typeof ApiLinksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/units': typeof AppUnitsRoute
  '/api/containers': typeof ApiContainersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/units': typeof ApiUnitsRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/favicon/$key': typeof ApiFaviconKeyRoute
  '/api/icons/$slug': typeof ApiIconsSlugRoute
  '/api/layout/hidden': typeof ApiLayoutHiddenRoute
  '/api/links/$id': typeof ApiLinksIdRoute
  '/api/layout/': typeof ApiLayoutIndexRoute
  '/api/links/': typeof ApiLinksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/journal'
    | '/units'
    | '/api/containers'
    | '/api/events'
    | '/api/health'
    | '/api/journal'
    | '/api/units'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/setup'
    | '/api/favicon/$key'
    | '/api/icons/$slug'
    | '/api/layout/hidden'
    | '/api/links/$id'
    | '/api/layout/'
    | '/api/links/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/journal'
    | '/units'
    | '/api/containers'
    | '/api/events'
    | '/api/health'
    | '/api/journal'
    | '/api/units'
    | '/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/setup'
    | '/api/favicon/$key'
    | '/api/icons/$slug'
    | '/api/layout/hidden'
    | '/api/links/$id'
    | '/api/layout'
    | '/api/links'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/journal'
    | '/_app/units'
    | '/api/containers'
    | '/api/events'
    | '/api/health'
    | '/api/journal'
    | '/api/units'
    | '/_app/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/setup'
    | '/api/favicon/$key'
    | '/api/icons/$slug'
    | '/api/layout/hidden'
    | '/api/links/$id'
    | '/api/layout/'
    | '/api/links/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiContainersRoute: typeof ApiContainersRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiJournalRoute: typeof ApiJournalRoute
  ApiUnitsRoute: typeof ApiUnitsRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSetupRoute: typeof ApiAuthSetupRoute
  ApiFaviconKeyRoute: typeof ApiFaviconKeyRoute
  ApiIconsSlugRoute: typeof ApiIconsSlugRoute
  ApiLayoutHiddenRoute: typeof ApiLayoutHiddenRoute
  ApiLinksIdRoute: typeof ApiLinksIdRoute
  ApiLayoutIndexRoute: typeof ApiLayoutIndexRoute
  ApiLinksIndexRoute: typeof ApiLinksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/units': {
      id: '/_app/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AppUnitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/containers': {
      id: '/api/containers'
      path: '/api/containers'
      fullPath: '/api/containers'
      preLoaderRoute: typeof ApiContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/journal': {
      id: '/api/journal'
      path: '/api/journal'
      fullPath: '/api/journal'
      preLoaderRoute: typeof ApiJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/units': {
      id: '/api/units'
      path: '/api/units'
      fullPath: '/api/units'
      preLoaderRoute: typeof ApiUnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/setup': {
      id: '/api/auth/setup'
      path: '/api/auth/setup'
      fullPath: '/api/auth/setup'
      preLoaderRoute: typeof ApiAuthSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/favicon/$key': {
      id: '/api/favicon/$key'
      path: '/api/favicon/$key'
      fullPath: '/api/favicon/$key'
      preLoaderRoute: typeof ApiFaviconKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/icons/$slug': {
      id: '/api/icons/$slug'
      path: '/api/icons/$slug'
      fullPath: '/api/icons/$slug'
      preLoaderRoute: typeof ApiIconsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/layout/': {
      id: '/api/layout/'
      path: '/api/layout'
      fullPath: '/api/layout/'
      preLoaderRoute: typeof ApiLayoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/layout/hidden': {
      id: '/api/layout/hidden'
      path: '/api/layout/hidden'
      fullPath: '/api/layout/hidden'
      preLoaderRoute: typeof ApiLayoutHiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/links/': {
      id: '/api/links/'
      path: '/api/links'
      fullPath: '/api/links/'
      preLoaderRoute: typeof ApiLinksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/links/$id': {
      id: '/api/links/$id'
      path: '/api/links/$id'
      fullPath: '/api/links/$id'
      preLoaderRoute: typeof ApiLinksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppJournalRoute: typeof AppJournalRoute
  AppUnitsRoute: typeof AppUnitsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppJournalRoute: AppJournalRoute,
  AppUnitsRoute: AppUnitsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiContainersRoute: ApiContainersRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiJournalRoute: ApiJournalRoute,
  ApiUnitsRoute: ApiUnitsRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSetupRoute: ApiAuthSetupRoute,
  ApiFaviconKeyRoute: ApiFaviconKeyRoute,
  ApiIconsSlugRoute: ApiIconsSlugRoute,
  ApiLayoutHiddenRoute: ApiLayoutHiddenRoute,
  ApiLinksIdRoute: ApiLinksIdRoute,
  ApiLayoutIndexRoute: ApiLayoutIndexRoute,
  ApiLinksIndexRoute: ApiLinksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
