/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppJournalRouteImport } from './routes/_app/journal'
import { Route as AppSystemRouteImport } from './routes/_app/system'
import { Route as AppUnitsRouteImport } from './routes/_app/units'
import { Route as ApiContainersRouteImport } from './routes/api/containers'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiJournalRouteImport } from './routes/api/journal'
import { Route as ApiUnitsRouteImport } from './routes/api/units'
import { Route as ApiUnlockRouteImport } from './routes/api/unlock'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthSetupRouteImport } from './routes/api/auth/setup'
import { Route as ApiFaviconKeyRouteImport } from './routes/api/favicon/$key'
import { Route as ApiIconsSlugRouteImport } from './routes/api/icons/$slug'
import { Route as ApiIconsSearchRouteImport } from './routes/api/icons/search'
import { Route as ApiJobsIndexRouteImport } from './routes/api/jobs/index'
import { Route as ApiJobsIdRouteImport } from './routes/api/jobs/$id'
import { Route as ApiLayoutIndexRouteImport } from './routes/api/layout/index'
import { Route as ApiLayoutHiddenRouteImport } from './routes/api/layout/hidden'
import { Route as ApiLinksIndexRouteImport } from './routes/api/links/index'
import { Route as ApiLinksIdRouteImport } from './routes/api/links/$id'
import { Route as ApiServicesOverrideRouteImport } from './routes/api/services/override'
import { Route as ApiSystemImagesRouteImport } from './routes/api/system/images'
import { Route as ApiSystemOverviewRouteImport } from './routes/api/system/overview'
import { Route as ApiSystemRemovePreviewRouteImport } from './routes/api/system/remove-preview'
import { Route as ApiSystemUpdatesRouteImport } from './routes/api/system/updates'
import { Route as ApiSystemPackagesIndexRouteImport } from './routes/api/system/packages/index'
import { Route as ApiSystemPackagesNameRouteImport } from './routes/api/system/packages/$name'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const AppUnitsRoute = AppUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppRoute,
} as any)
const ApiContainersRoute = ApiContainersRouteImport.update({
  id: '/api/containers',
  path: '/api/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJournalRoute = ApiJournalRouteImport.update({
  id: '/api/journal',
  path: '/api/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnitsRoute = ApiUnitsRouteImport.update({
  id: '/api/units',
  path: '/api/units',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnlockRoute = ApiUnlockRouteImport.update({
  id: '/api/unlock',
  path: '/api/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSetupRoute = ApiAuthSetupRouteImport.update({
  id: '/api/auth/setup',
  path: '/api/auth/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFaviconKeyRoute = ApiFaviconKeyRouteImport.update({
  id: '/api/favicon/$key',
  path: '/api/favicon/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIconsSlugRoute = ApiIconsSlugRouteImport.update({
  id: '/api/icons/$slug',
  path: '/api/icons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIconsSearchRoute = ApiIconsSearchRouteImport.update({
  id: '/api/icons/search',
  path: '/api/icons/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIndexRoute = ApiJobsIndexRouteImport.update({
  id: '/api/jobs/',
  path: '/api/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdRoute = ApiJobsIdRouteImport.update({
  id: '/api/jobs/$id',
  path: '/api/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLayoutIndexRoute = ApiLayoutIndexRouteImport.update({
  id: '/api/layout/',
  path: '/api/layout/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLayoutHiddenRoute = ApiLayoutHiddenRouteImport.update({
  id: '/api/layout/hidden',
  path: '/api/layout/hidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinksIndexRoute = ApiLinksIndexRouteImport.update({
  id: '/api/links/',
  path: '/api/links/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinksIdRoute = ApiLinksIdRouteImport.update({
  id: '/api/links/$id',
  path: '/api/links/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServicesOverrideRoute = ApiServicesOverrideRouteImport.update({
  id: '/api/services/override',
  path: '/api/services/override',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemImagesRoute = ApiSystemImagesRouteImport.update({
  id: '/api/system/images',
  path: '/api/system/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemOverviewRoute = ApiSystemOverviewRouteImport.update({
  id: '/api/system/overview',
  path: '/api/system/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemRemovePreviewRoute = ApiSystemRemovePreviewRouteImport.update({
  id: '/api/system/remove-preview',
  path: '/api/system/remove-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemUpdatesRoute = ApiSystemUpdatesRouteImport.update({
  id: '/api/system/updates',
  path: '/api/system/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemPackagesIndexRoute = ApiSystemPackagesIndexRouteImport.update({
  id: '/api/system/packages/',
  path: '/api/system/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemPackagesNameRoute = ApiSystemPackagesNameRouteImport.update({
  id: '/api/system/packages/$name',
  path: '/api/system/packages/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/journal': typeof AppJournalRoute
  '/system': typeof AppSystemRoute
  '/units': typeof AppUnitsRoute
  '/api/containers': typeof ApiContainersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/units': typeof ApiUnitsRoute
  '/api/unlock': typeof ApiUnlockRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/favicon/$key': typeof ApiFaviconKeyRoute
  '/api/icons/$slug': typeof ApiIconsSlugRoute
  '/api/icons/search': typeof ApiIconsSearchRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/layout/hidden': typeof ApiLayoutHiddenRoute
  '/api/links/$id': typeof ApiLinksIdRoute
  '/api/services/override': typeof ApiServicesOverrideRoute
  '/api/system/images': typeof ApiSystemImagesRoute
  '/api/system/overview': typeof ApiSystemOverviewRoute
  '/api/system/remove-preview': typeof ApiSystemRemovePreviewRoute
  '/api/system/updates': typeof ApiSystemUpdatesRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/layout/': typeof ApiLayoutIndexRoute
  '/api/links/': typeof ApiLinksIndexRoute
  '/api/system/packages/$name': typeof ApiSystemPackagesNameRoute
  '/api/system/packages/': typeof ApiSystemPackagesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/journal': typeof AppJournalRoute
  '/system': typeof AppSystemRoute
  '/units': typeof AppUnitsRoute
  '/api/containers': typeof ApiContainersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/units': typeof ApiUnitsRoute
  '/api/unlock': typeof ApiUnlockRoute
  '/': typeof AppIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/favicon/$key': typeof ApiFaviconKeyRoute
  '/api/icons/$slug': typeof ApiIconsSlugRoute
  '/api/icons/search': typeof ApiIconsSearchRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/layout/hidden': typeof ApiLayoutHiddenRoute
  '/api/links/$id': typeof ApiLinksIdRoute
  '/api/services/override': typeof ApiServicesOverrideRoute
  '/api/system/images': typeof ApiSystemImagesRoute
  '/api/system/overview': typeof ApiSystemOverviewRoute
  '/api/system/remove-preview': typeof ApiSystemRemovePreviewRoute
  '/api/system/updates': typeof ApiSystemUpdatesRoute
  '/api/jobs': typeof ApiJobsIndexRoute
  '/api/layout': typeof ApiLayoutIndexRoute
  '/api/links': typeof ApiLinksIndexRoute
  '/api/system/packages/$name': typeof ApiSystemPackagesNameRoute
  '/api/system/packages': typeof ApiSystemPackagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/system': typeof AppSystemRoute
  '/_app/units': typeof AppUnitsRoute
  '/api/containers': typeof ApiContainersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/units': typeof ApiUnitsRoute
  '/api/unlock': typeof ApiUnlockRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/favicon/$key': typeof ApiFaviconKeyRoute
  '/api/icons/$slug': typeof ApiIconsSlugRoute
  '/api/icons/search': typeof ApiIconsSearchRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/layout/hidden': typeof ApiLayoutHiddenRoute
  '/api/links/$id': typeof ApiLinksIdRoute
  '/api/services/override': typeof ApiServicesOverrideRoute
  '/api/system/images': typeof ApiSystemImagesRoute
  '/api/system/overview': typeof ApiSystemOverviewRoute
  '/api/system/remove-preview': typeof ApiSystemRemovePreviewRoute
  '/api/system/updates': typeof ApiSystemUpdatesRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/layout/': typeof ApiLayoutIndexRoute
  '/api/links/': typeof ApiLinksIndexRoute
  '/api/system/packages/$name': typeof ApiSystemPackagesNameRoute
  '/api/system/packages/': typeof ApiSystemPackagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/journal'
    | '/system'
    | '/units'
    | '/api/containers'
    | '/api/events'
    | '/api/health'
    | '/api/journal'
    | '/api/units'
    | '/api/unlock'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/setup'
    | '/api/favicon/$key'
    | '/api/icons/$slug'
    | '/api/icons/search'
    | '/api/jobs/$id'
    | '/api/layout/hidden'
    | '/api/links/$id'
    | '/api/services/override'
    | '/api/system/images'
    | '/api/system/overview'
    | '/api/system/remove-preview'
    | '/api/system/updates'
    | '/api/jobs/'
    | '/api/layout/'
    | '/api/links/'
    | '/api/system/packages/$name'
    | '/api/system/packages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/journal'
    | '/system'
    | '/units'
    | '/api/containers'
    | '/api/events'
    | '/api/health'
    | '/api/journal'
    | '/api/units'
    | '/api/unlock'
    | '/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/setup'
    | '/api/favicon/$key'
    | '/api/icons/$slug'
    | '/api/icons/search'
    | '/api/jobs/$id'
    | '/api/layout/hidden'
    | '/api/links/$id'
    | '/api/services/override'
    | '/api/system/images'
    | '/api/system/overview'
    | '/api/system/remove-preview'
    | '/api/system/updates'
    | '/api/jobs'
    | '/api/layout'
    | '/api/links'
    | '/api/system/packages/$name'
    | '/api/system/packages'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/journal'
    | '/_app/system'
    | '/_app/units'
    | '/api/containers'
    | '/api/events'
    | '/api/health'
    | '/api/journal'
    | '/api/units'
    | '/api/unlock'
    | '/_app/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/setup'
    | '/api/favicon/$key'
    | '/api/icons/$slug'
    | '/api/icons/search'
    | '/api/jobs/$id'
    | '/api/layout/hidden'
    | '/api/links/$id'
    | '/api/services/override'
    | '/api/system/images'
    | '/api/system/overview'
    | '/api/system/remove-preview'
    | '/api/system/updates'
    | '/api/jobs/'
    | '/api/layout/'
    | '/api/links/'
    | '/api/system/packages/$name'
    | '/api/system/packages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiContainersRoute: typeof ApiContainersRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiJournalRoute: typeof ApiJournalRoute
  ApiUnitsRoute: typeof ApiUnitsRoute
  ApiUnlockRoute: typeof ApiUnlockRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSetupRoute: typeof ApiAuthSetupRoute
  ApiFaviconKeyRoute: typeof ApiFaviconKeyRoute
  ApiIconsSlugRoute: typeof ApiIconsSlugRoute
  ApiIconsSearchRoute: typeof ApiIconsSearchRoute
  ApiJobsIdRoute: typeof ApiJobsIdRoute
  ApiLayoutHiddenRoute: typeof ApiLayoutHiddenRoute
  ApiLinksIdRoute: typeof ApiLinksIdRoute
  ApiServicesOverrideRoute: typeof ApiServicesOverrideRoute
  ApiSystemImagesRoute: typeof ApiSystemImagesRoute
  ApiSystemOverviewRoute: typeof ApiSystemOverviewRoute
  ApiSystemRemovePreviewRoute: typeof ApiSystemRemovePreviewRoute
  ApiSystemUpdatesRoute: typeof ApiSystemUpdatesRoute
  ApiJobsIndexRoute: typeof ApiJobsIndexRoute
  ApiLayoutIndexRoute: typeof ApiLayoutIndexRoute
  ApiLinksIndexRoute: typeof ApiLinksIndexRoute
  ApiSystemPackagesNameRoute: typeof ApiSystemPackagesNameRoute
  ApiSystemPackagesIndexRoute: typeof ApiSystemPackagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/units': {
      id: '/_app/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AppUnitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/containers': {
      id: '/api/containers'
      path: '/api/containers'
      fullPath: '/api/containers'
      preLoaderRoute: typeof ApiContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/journal': {
      id: '/api/journal'
      path: '/api/journal'
      fullPath: '/api/journal'
      preLoaderRoute: typeof ApiJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/units': {
      id: '/api/units'
      path: '/api/units'
      fullPath: '/api/units'
      preLoaderRoute: typeof ApiUnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unlock': {
      id: '/api/unlock'
      path: '/api/unlock'
      fullPath: '/api/unlock'
      preLoaderRoute: typeof ApiUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/setup': {
      id: '/api/auth/setup'
      path: '/api/auth/setup'
      fullPath: '/api/auth/setup'
      preLoaderRoute: typeof ApiAuthSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/favicon/$key': {
      id: '/api/favicon/$key'
      path: '/api/favicon/$key'
      fullPath: '/api/favicon/$key'
      preLoaderRoute: typeof ApiFaviconKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/icons/$slug': {
      id: '/api/icons/$slug'
      path: '/api/icons/$slug'
      fullPath: '/api/icons/$slug'
      preLoaderRoute: typeof ApiIconsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/icons/search': {
      id: '/api/icons/search'
      path: '/api/icons/search'
      fullPath: '/api/icons/search'
      preLoaderRoute: typeof ApiIconsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/': {
      id: '/api/jobs/'
      path: '/api/jobs'
      fullPath: '/api/jobs/'
      preLoaderRoute: typeof ApiJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id': {
      id: '/api/jobs/$id'
      path: '/api/jobs/$id'
      fullPath: '/api/jobs/$id'
      preLoaderRoute: typeof ApiJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/layout/': {
      id: '/api/layout/'
      path: '/api/layout'
      fullPath: '/api/layout/'
      preLoaderRoute: typeof ApiLayoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/layout/hidden': {
      id: '/api/layout/hidden'
      path: '/api/layout/hidden'
      fullPath: '/api/layout/hidden'
      preLoaderRoute: typeof ApiLayoutHiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/links/': {
      id: '/api/links/'
      path: '/api/links'
      fullPath: '/api/links/'
      preLoaderRoute: typeof ApiLinksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/links/$id': {
      id: '/api/links/$id'
      path: '/api/links/$id'
      fullPath: '/api/links/$id'
      preLoaderRoute: typeof ApiLinksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/services/override': {
      id: '/api/services/override'
      path: '/api/services/override'
      fullPath: '/api/services/override'
      preLoaderRoute: typeof ApiServicesOverrideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/images': {
      id: '/api/system/images'
      path: '/api/system/images'
      fullPath: '/api/system/images'
      preLoaderRoute: typeof ApiSystemImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/overview': {
      id: '/api/system/overview'
      path: '/api/system/overview'
      fullPath: '/api/system/overview'
      preLoaderRoute: typeof ApiSystemOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/remove-preview': {
      id: '/api/system/remove-preview'
      path: '/api/system/remove-preview'
      fullPath: '/api/system/remove-preview'
      preLoaderRoute: typeof ApiSystemRemovePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/updates': {
      id: '/api/system/updates'
      path: '/api/system/updates'
      fullPath: '/api/system/updates'
      preLoaderRoute: typeof ApiSystemUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/packages/': {
      id: '/api/system/packages/'
      path: '/api/system/packages'
      fullPath: '/api/system/packages/'
      preLoaderRoute: typeof ApiSystemPackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/packages/$name': {
      id: '/api/system/packages/$name'
      path: '/api/system/packages/$name'
      fullPath: '/api/system/packages/$name'
      preLoaderRoute: typeof ApiSystemPackagesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppJournalRoute: typeof AppJournalRoute
  AppSystemRoute: typeof AppSystemRoute
  AppUnitsRoute: typeof AppUnitsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppJournalRoute: AppJournalRoute,
  AppSystemRoute: AppSystemRoute,
  AppUnitsRoute: AppUnitsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiContainersRoute: ApiContainersRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiJournalRoute: ApiJournalRoute,
  ApiUnitsRoute: ApiUnitsRoute,
  ApiUnlockRoute: ApiUnlockRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSetupRoute: ApiAuthSetupRoute,
  ApiFaviconKeyRoute: ApiFaviconKeyRoute,
  ApiIconsSlugRoute: ApiIconsSlugRoute,
  ApiIconsSearchRoute: ApiIconsSearchRoute,
  ApiJobsIdRoute: ApiJobsIdRoute,
  ApiLayoutHiddenRoute: ApiLayoutHiddenRoute,
  ApiLinksIdRoute: ApiLinksIdRoute,
  ApiServicesOverrideRoute: ApiServicesOverrideRoute,
  ApiSystemImagesRoute: ApiSystemImagesRoute,
  ApiSystemOverviewRoute: ApiSystemOverviewRoute,
  ApiSystemRemovePreviewRoute: ApiSystemRemovePreviewRoute,
  ApiSystemUpdatesRoute: ApiSystemUpdatesRoute,
  ApiJobsIndexRoute: ApiJobsIndexRoute,
  ApiLayoutIndexRoute: ApiLayoutIndexRoute,
  ApiLinksIndexRoute: ApiLinksIndexRoute,
  ApiSystemPackagesNameRoute: ApiSystemPackagesNameRoute,
  ApiSystemPackagesIndexRoute: ApiSystemPackagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
