/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBackupsRouteImport } from './routes/_app/backups'
import { Route as AppDisksRouteImport } from './routes/_app/disks'
import { Route as AppFilesRouteImport } from './routes/_app/files'
import { Route as AppHardwareRouteImport } from './routes/_app/hardware'
import { Route as AppJournalRouteImport } from './routes/_app/journal'
import { Route as AppNetworkRouteImport } from './routes/_app/network'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppQuadletsRouteImport } from './routes/_app/quadlets'
import { Route as AppSharesRouteImport } from './routes/_app/shares'
import { Route as AppSshRouteImport } from './routes/_app/ssh'
import { Route as AppSystemRouteImport } from './routes/_app/system'
import { Route as AppSystemdRouteImport } from './routes/_app/systemd'
import { Route as AppUnitsRouteImport } from './routes/_app/units'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as ApiContainersRouteImport } from './routes/api/containers'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiJournalRouteImport } from './routes/api/journal'
import { Route as ApiLangRouteImport } from './routes/api/lang'
import { Route as ApiUnitsRouteImport } from './routes/api/units'
import { Route as ApiUnlockRouteImport } from './routes/api/unlock'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthSetupRouteImport } from './routes/api/auth/setup'
import { Route as ApiBackupIndexRouteImport } from './routes/api/backup/index'
import { Route as ApiBootIndexRouteImport } from './routes/api/boot/index'
import { Route as ApiCaddyIndexRouteImport } from './routes/api/caddy/index'
import { Route as ApiDisksPowerRouteImport } from './routes/api/disks/power'
import { Route as ApiDisksSmartRouteImport } from './routes/api/disks/smart'
import { Route as ApiFaviconKeyRouteImport } from './routes/api/favicon/$key'
import { Route as ApiFilesIndexRouteImport } from './routes/api/files/index'
import { Route as ApiFstabIndexRouteImport } from './routes/api/fstab/index'
import { Route as ApiHardwareIndexRouteImport } from './routes/api/hardware/index'
import { Route as ApiIconsSlugRouteImport } from './routes/api/icons/$slug'
import { Route as ApiIconsSearchRouteImport } from './routes/api/icons/search'
import { Route as ApiJobsIndexRouteImport } from './routes/api/jobs/index'
import { Route as ApiJobsIdRouteImport } from './routes/api/jobs/$id'
import { Route as ApiLayoutIndexRouteImport } from './routes/api/layout/index'
import { Route as ApiLayoutHiddenRouteImport } from './routes/api/layout/hidden'
import { Route as ApiLinksIndexRouteImport } from './routes/api/links/index'
import { Route as ApiLinksIdRouteImport } from './routes/api/links/$id'
import { Route as ApiMetricsContainersRouteImport } from './routes/api/metrics/containers'
import { Route as ApiMetricsHistoryRouteImport } from './routes/api/metrics/history'
import { Route as ApiNetworkIndexRouteImport } from './routes/api/network/index'
import { Route as ApiNetworkDevicesRouteImport } from './routes/api/network/devices'
import { Route as ApiNotificationsIndexRouteImport } from './routes/api/notifications/index'
import { Route as ApiPodmanSettingsRouteImport } from './routes/api/podman/settings'
import { Route as ApiPodmanStorageRouteImport } from './routes/api/podman/storage'
import { Route as ApiPowerIndexRouteImport } from './routes/api/power/index'
import { Route as ApiQuadletsIndexRouteImport } from './routes/api/quadlets/index'
import { Route as ApiQuadletsComposeRouteImport } from './routes/api/quadlets/compose'
import { Route as ApiQuadletsFileRouteImport } from './routes/api/quadlets/file'
import { Route as ApiQuadletsRevisionRouteImport } from './routes/api/quadlets/revision'
import { Route as ApiQuadletsValidateRouteImport } from './routes/api/quadlets/validate'
import { Route as ApiServicesOverrideRouteImport } from './routes/api/services/override'
import { Route as ApiSharesIndexRouteImport } from './routes/api/shares/index'
import { Route as ApiSpeedtestIndexRouteImport } from './routes/api/speedtest/index'
import { Route as ApiSshIndexRouteImport } from './routes/api/ssh/index'
import { Route as ApiSystemConfigRouteImport } from './routes/api/system/config'
import { Route as ApiSystemImagesRouteImport } from './routes/api/system/images'
import { Route as ApiSystemOverviewRouteImport } from './routes/api/system/overview'
import { Route as ApiSystemRemovePreviewRouteImport } from './routes/api/system/remove-preview'
import { Route as ApiSystemUpdatesRouteImport } from './routes/api/system/updates'
import { Route as ApiSystemdIndexRouteImport } from './routes/api/systemd/index'
import { Route as ApiTimersIndexRouteImport } from './routes/api/timers/index'
import { Route as ApiUsersIndexRouteImport } from './routes/api/users/index'
import { Route as ApiBackupScriptTokenRouteImport } from './routes/api/backup/script/$token'
import { Route as ApiSystemPackagesIndexRouteImport } from './routes/api/system/packages/index'
import { Route as ApiSystemPackagesNameRouteImport } from './routes/api/system/packages/$name'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupsRoute = AppBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AppRoute,
} as any)
const AppDisksRoute = AppDisksRouteImport.update({
  id: '/disks',
  path: '/disks',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppHardwareRoute = AppHardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppQuadletsRoute = AppQuadletsRouteImport.update({
  id: '/quadlets',
  path: '/quadlets',
  getParentRoute: () => AppRoute,
} as any)
const AppSharesRoute = AppSharesRouteImport.update({
  id: '/shares',
  path: '/shares',
  getParentRoute: () => AppRoute,
} as any)
const AppSshRoute = AppSshRouteImport.update({
  id: '/ssh',
  path: '/ssh',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemdRoute = AppSystemdRouteImport.update({
  id: '/systemd',
  path: '/systemd',
  getParentRoute: () => AppRoute,
} as any)
const AppUnitsRoute = AppUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const ApiContainersRoute = ApiContainersRouteImport.update({
  id: '/api/containers',
  path: '/api/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJournalRoute = ApiJournalRouteImport.update({
  id: '/api/journal',
  path: '/api/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLangRoute = ApiLangRouteImport.update({
  id: '/api/lang',
  path: '/api/lang',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnitsRoute = ApiUnitsRouteImport.update({
  id: '/api/units',
  path: '/api/units',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnlockRoute = ApiUnlockRouteImport.update({
  id: '/api/unlock',
  path: '/api/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSetupRoute = ApiAuthSetupRouteImport.update({
  id: '/api/auth/setup',
  path: '/api/auth/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackupIndexRoute = ApiBackupIndexRouteImport.update({
  id: '/api/backup/',
  path: '/api/backup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBootIndexRoute = ApiBootIndexRouteImport.update({
  id: '/api/boot/',
  path: '/api/boot/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaddyIndexRoute = ApiCaddyIndexRouteImport.update({
  id: '/api/caddy/',
  path: '/api/caddy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisksPowerRoute = ApiDisksPowerRouteImport.update({
  id: '/api/disks/power',
  path: '/api/disks/power',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisksSmartRoute = ApiDisksSmartRouteImport.update({
  id: '/api/disks/smart',
  path: '/api/disks/smart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFaviconKeyRoute = ApiFaviconKeyRouteImport.update({
  id: '/api/favicon/$key',
  path: '/api/favicon/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesIndexRoute = ApiFilesIndexRouteImport.update({
  id: '/api/files/',
  path: '/api/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFstabIndexRoute = ApiFstabIndexRouteImport.update({
  id: '/api/fstab/',
  path: '/api/fstab/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHardwareIndexRoute = ApiHardwareIndexRouteImport.update({
  id: '/api/hardware/',
  path: '/api/hardware/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIconsSlugRoute = ApiIconsSlugRouteImport.update({
  id: '/api/icons/$slug',
  path: '/api/icons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIconsSearchRoute = ApiIconsSearchRouteImport.update({
  id: '/api/icons/search',
  path: '/api/icons/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIndexRoute = ApiJobsIndexRouteImport.update({
  id: '/api/jobs/',
  path: '/api/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdRoute = ApiJobsIdRouteImport.update({
  id: '/api/jobs/$id',
  path: '/api/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLayoutIndexRoute = ApiLayoutIndexRouteImport.update({
  id: '/api/layout/',
  path: '/api/layout/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLayoutHiddenRoute = ApiLayoutHiddenRouteImport.update({
  id: '/api/layout/hidden',
  path: '/api/layout/hidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinksIndexRoute = ApiLinksIndexRouteImport.update({
  id: '/api/links/',
  path: '/api/links/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinksIdRoute = ApiLinksIdRouteImport.update({
  id: '/api/links/$id',
  path: '/api/links/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetricsContainersRoute = ApiMetricsContainersRouteImport.update({
  id: '/api/metrics/containers',
  path: '/api/metrics/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetricsHistoryRoute = ApiMetricsHistoryRouteImport.update({
  id: '/api/metrics/history',
  path: '/api/metrics/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNetworkIndexRoute = ApiNetworkIndexRouteImport.update({
  id: '/api/network/',
  path: '/api/network/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNetworkDevicesRoute = ApiNetworkDevicesRouteImport.update({
  id: '/api/network/devices',
  path: '/api/network/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsIndexRoute = ApiNotificationsIndexRouteImport.update({
  id: '/api/notifications/',
  path: '/api/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPodmanSettingsRoute = ApiPodmanSettingsRouteImport.update({
  id: '/api/podman/settings',
  path: '/api/podman/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPodmanStorageRoute = ApiPodmanStorageRouteImport.update({
  id: '/api/podman/storage',
  path: '/api/podman/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPowerIndexRoute = ApiPowerIndexRouteImport.update({
  id: '/api/power/',
  path: '/api/power/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuadletsIndexRoute = ApiQuadletsIndexRouteImport.update({
  id: '/api/quadlets/',
  path: '/api/quadlets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuadletsComposeRoute = ApiQuadletsComposeRouteImport.update({
  id: '/api/quadlets/compose',
  path: '/api/quadlets/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuadletsFileRoute = ApiQuadletsFileRouteImport.update({
  id: '/api/quadlets/file',
  path: '/api/quadlets/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuadletsRevisionRoute = ApiQuadletsRevisionRouteImport.update({
  id: '/api/quadlets/revision',
  path: '/api/quadlets/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuadletsValidateRoute = ApiQuadletsValidateRouteImport.update({
  id: '/api/quadlets/validate',
  path: '/api/quadlets/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServicesOverrideRoute = ApiServicesOverrideRouteImport.update({
  id: '/api/services/override',
  path: '/api/services/override',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharesIndexRoute = ApiSharesIndexRouteImport.update({
  id: '/api/shares/',
  path: '/api/shares/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeedtestIndexRoute = ApiSpeedtestIndexRouteImport.update({
  id: '/api/speedtest/',
  path: '/api/speedtest/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSshIndexRoute = ApiSshIndexRouteImport.update({
  id: '/api/ssh/',
  path: '/api/ssh/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemConfigRoute = ApiSystemConfigRouteImport.update({
  id: '/api/system/config',
  path: '/api/system/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemImagesRoute = ApiSystemImagesRouteImport.update({
  id: '/api/system/images',
  path: '/api/system/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemOverviewRoute = ApiSystemOverviewRouteImport.update({
  id: '/api/system/overview',
  path: '/api/system/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemRemovePreviewRoute = ApiSystemRemovePreviewRouteImport.update({
  id: '/api/system/remove-preview',
  path: '/api/system/remove-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemUpdatesRoute = ApiSystemUpdatesRouteImport.update({
  id: '/api/system/updates',
  path: '/api/system/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemdIndexRoute = ApiSystemdIndexRouteImport.update({
  id: '/api/systemd/',
  path: '/api/systemd/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTimersIndexRoute = ApiTimersIndexRouteImport.update({
  id: '/api/timers/',
  path: '/api/timers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIndexRoute = ApiUsersIndexRouteImport.update({
  id: '/api/users/',
  path: '/api/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackupScriptTokenRoute = ApiBackupScriptTokenRouteImport.update({
  id: '/api/backup/script/$token',
  path: '/api/backup/script/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemPackagesIndexRoute = ApiSystemPackagesIndexRouteImport.update({
  id: '/api/system/packages/',
  path: '/api/system/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemPackagesNameRoute = ApiSystemPackagesNameRouteImport.update({
  id: '/api/system/packages/$name',
  path: '/api/system/packages/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/backups': typeof AppBackupsRoute
  '/disks': typeof AppDisksRoute
  '/files': typeof AppFilesRoute
  '/hardware': typeof AppHardwareRoute
  '/journal': typeof AppJournalRoute
  '/network': typeof AppNetworkRoute
  '/notifications': typeof AppNotificationsRoute
  '/quadlets': typeof AppQuadletsRoute
  '/shares': typeof AppSharesRoute
  '/ssh': typeof AppSshRoute
  '/system': typeof AppSystemRoute
  '/systemd': typeof AppSystemdRoute
  '/units': typeof AppUnitsRoute
  '/users': typeof AppUsersRoute
  '/api/containers': typeof ApiContainersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/lang': typeof ApiLangRoute
  '/api/units': typeof ApiUnitsRoute
  '/api/unlock': typeof ApiUnlockRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/disks/power': typeof ApiDisksPowerRoute
  '/api/disks/smart': typeof ApiDisksSmartRoute
  '/api/favicon/$key': typeof ApiFaviconKeyRoute
  '/api/icons/$slug': typeof ApiIconsSlugRoute
  '/api/icons/search': typeof ApiIconsSearchRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/layout/hidden': typeof ApiLayoutHiddenRoute
  '/api/links/$id': typeof ApiLinksIdRoute
  '/api/metrics/containers': typeof ApiMetricsContainersRoute
  '/api/metrics/history': typeof ApiMetricsHistoryRoute
  '/api/network/devices': typeof ApiNetworkDevicesRoute
  '/api/podman/settings': typeof ApiPodmanSettingsRoute
  '/api/podman/storage': typeof ApiPodmanStorageRoute
  '/api/quadlets/compose': typeof ApiQuadletsComposeRoute
  '/api/quadlets/file': typeof ApiQuadletsFileRoute
  '/api/quadlets/revision': typeof ApiQuadletsRevisionRoute
  '/api/quadlets/validate': typeof ApiQuadletsValidateRoute
  '/api/services/override': typeof ApiServicesOverrideRoute
  '/api/system/config': typeof ApiSystemConfigRoute
  '/api/system/images': typeof ApiSystemImagesRoute
  '/api/system/overview': typeof ApiSystemOverviewRoute
  '/api/system/remove-preview': typeof ApiSystemRemovePreviewRoute
  '/api/system/updates': typeof ApiSystemUpdatesRoute
  '/api/backup/': typeof ApiBackupIndexRoute
  '/api/boot/': typeof ApiBootIndexRoute
  '/api/caddy/': typeof ApiCaddyIndexRoute
  '/api/files/': typeof ApiFilesIndexRoute
  '/api/fstab/': typeof ApiFstabIndexRoute
  '/api/hardware/': typeof ApiHardwareIndexRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/layout/': typeof ApiLayoutIndexRoute
  '/api/links/': typeof ApiLinksIndexRoute
  '/api/network/': typeof ApiNetworkIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/api/power/': typeof ApiPowerIndexRoute
  '/api/quadlets/': typeof ApiQuadletsIndexRoute
  '/api/shares/': typeof ApiSharesIndexRoute
  '/api/speedtest/': typeof ApiSpeedtestIndexRoute
  '/api/ssh/': typeof ApiSshIndexRoute
  '/api/systemd/': typeof ApiSystemdIndexRoute
  '/api/timers/': typeof ApiTimersIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
  '/api/backup/script/$token': typeof ApiBackupScriptTokenRoute
  '/api/system/packages/$name': typeof ApiSystemPackagesNameRoute
  '/api/system/packages/': typeof ApiSystemPackagesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/backups': typeof AppBackupsRoute
  '/disks': typeof AppDisksRoute
  '/files': typeof AppFilesRoute
  '/hardware': typeof AppHardwareRoute
  '/journal': typeof AppJournalRoute
  '/network': typeof AppNetworkRoute
  '/notifications': typeof AppNotificationsRoute
  '/quadlets': typeof AppQuadletsRoute
  '/shares': typeof AppSharesRoute
  '/ssh': typeof AppSshRoute
  '/system': typeof AppSystemRoute
  '/systemd': typeof AppSystemdRoute
  '/units': typeof AppUnitsRoute
  '/users': typeof AppUsersRoute
  '/api/containers': typeof ApiContainersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/lang': typeof ApiLangRoute
  '/api/units': typeof ApiUnitsRoute
  '/api/unlock': typeof ApiUnlockRoute
  '/': typeof AppIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/disks/power': typeof ApiDisksPowerRoute
  '/api/disks/smart': typeof ApiDisksSmartRoute
  '/api/favicon/$key': typeof ApiFaviconKeyRoute
  '/api/icons/$slug': typeof ApiIconsSlugRoute
  '/api/icons/search': typeof ApiIconsSearchRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/layout/hidden': typeof ApiLayoutHiddenRoute
  '/api/links/$id': typeof ApiLinksIdRoute
  '/api/metrics/containers': typeof ApiMetricsContainersRoute
  '/api/metrics/history': typeof ApiMetricsHistoryRoute
  '/api/network/devices': typeof ApiNetworkDevicesRoute
  '/api/podman/settings': typeof ApiPodmanSettingsRoute
  '/api/podman/storage': typeof ApiPodmanStorageRoute
  '/api/quadlets/compose': typeof ApiQuadletsComposeRoute
  '/api/quadlets/file': typeof ApiQuadletsFileRoute
  '/api/quadlets/revision': typeof ApiQuadletsRevisionRoute
  '/api/quadlets/validate': typeof ApiQuadletsValidateRoute
  '/api/services/override': typeof ApiServicesOverrideRoute
  '/api/system/config': typeof ApiSystemConfigRoute
  '/api/system/images': typeof ApiSystemImagesRoute
  '/api/system/overview': typeof ApiSystemOverviewRoute
  '/api/system/remove-preview': typeof ApiSystemRemovePreviewRoute
  '/api/system/updates': typeof ApiSystemUpdatesRoute
  '/api/backup': typeof ApiBackupIndexRoute
  '/api/boot': typeof ApiBootIndexRoute
  '/api/caddy': typeof ApiCaddyIndexRoute
  '/api/files': typeof ApiFilesIndexRoute
  '/api/fstab': typeof ApiFstabIndexRoute
  '/api/hardware': typeof ApiHardwareIndexRoute
  '/api/jobs': typeof ApiJobsIndexRoute
  '/api/layout': typeof ApiLayoutIndexRoute
  '/api/links': typeof ApiLinksIndexRoute
  '/api/network': typeof ApiNetworkIndexRoute
  '/api/notifications': typeof ApiNotificationsIndexRoute
  '/api/power': typeof ApiPowerIndexRoute
  '/api/quadlets': typeof ApiQuadletsIndexRoute
  '/api/shares': typeof ApiSharesIndexRoute
  '/api/speedtest': typeof ApiSpeedtestIndexRoute
  '/api/ssh': typeof ApiSshIndexRoute
  '/api/systemd': typeof ApiSystemdIndexRoute
  '/api/timers': typeof ApiTimersIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
  '/api/backup/script/$token': typeof ApiBackupScriptTokenRoute
  '/api/system/packages/$name': typeof ApiSystemPackagesNameRoute
  '/api/system/packages': typeof ApiSystemPackagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/backups': typeof AppBackupsRoute
  '/_app/disks': typeof AppDisksRoute
  '/_app/files': typeof AppFilesRoute
  '/_app/hardware': typeof AppHardwareRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/network': typeof AppNetworkRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/quadlets': typeof AppQuadletsRoute
  '/_app/shares': typeof AppSharesRoute
  '/_app/ssh': typeof AppSshRoute
  '/_app/system': typeof AppSystemRoute
  '/_app/systemd': typeof AppSystemdRoute
  '/_app/units': typeof AppUnitsRoute
  '/_app/users': typeof AppUsersRoute
  '/api/containers': typeof ApiContainersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/lang': typeof ApiLangRoute
  '/api/units': typeof ApiUnitsRoute
  '/api/unlock': typeof ApiUnlockRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/disks/power': typeof ApiDisksPowerRoute
  '/api/disks/smart': typeof ApiDisksSmartRoute
  '/api/favicon/$key': typeof ApiFaviconKeyRoute
  '/api/icons/$slug': typeof ApiIconsSlugRoute
  '/api/icons/search': typeof ApiIconsSearchRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/layout/hidden': typeof ApiLayoutHiddenRoute
  '/api/links/$id': typeof ApiLinksIdRoute
  '/api/metrics/containers': typeof ApiMetricsContainersRoute
  '/api/metrics/history': typeof ApiMetricsHistoryRoute
  '/api/network/devices': typeof ApiNetworkDevicesRoute
  '/api/podman/settings': typeof ApiPodmanSettingsRoute
  '/api/podman/storage': typeof ApiPodmanStorageRoute
  '/api/quadlets/compose': typeof ApiQuadletsComposeRoute
  '/api/quadlets/file': typeof ApiQuadletsFileRoute
  '/api/quadlets/revision': typeof ApiQuadletsRevisionRoute
  '/api/quadlets/validate': typeof ApiQuadletsValidateRoute
  '/api/services/override': typeof ApiServicesOverrideRoute
  '/api/system/config': typeof ApiSystemConfigRoute
  '/api/system/images': typeof ApiSystemImagesRoute
  '/api/system/overview': typeof ApiSystemOverviewRoute
  '/api/system/remove-preview': typeof ApiSystemRemovePreviewRoute
  '/api/system/updates': typeof ApiSystemUpdatesRoute
  '/api/backup/': typeof ApiBackupIndexRoute
  '/api/boot/': typeof ApiBootIndexRoute
  '/api/caddy/': typeof ApiCaddyIndexRoute
  '/api/files/': typeof ApiFilesIndexRoute
  '/api/fstab/': typeof ApiFstabIndexRoute
  '/api/hardware/': typeof ApiHardwareIndexRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/layout/': typeof ApiLayoutIndexRoute
  '/api/links/': typeof ApiLinksIndexRoute
  '/api/network/': typeof ApiNetworkIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/api/power/': typeof ApiPowerIndexRoute
  '/api/quadlets/': typeof ApiQuadletsIndexRoute
  '/api/shares/': typeof ApiSharesIndexRoute
  '/api/speedtest/': typeof ApiSpeedtestIndexRoute
  '/api/ssh/': typeof ApiSshIndexRoute
  '/api/systemd/': typeof ApiSystemdIndexRoute
  '/api/timers/': typeof ApiTimersIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
  '/api/backup/script/$token': typeof ApiBackupScriptTokenRoute
  '/api/system/packages/$name': typeof ApiSystemPackagesNameRoute
  '/api/system/packages/': typeof ApiSystemPackagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/backups'
    | '/disks'
    | '/files'
    | '/hardware'
    | '/journal'
    | '/network'
    | '/notifications'
    | '/quadlets'
    | '/shares'
    | '/ssh'
    | '/system'
    | '/systemd'
    | '/units'
    | '/users'
    | '/api/containers'
    | '/api/events'
    | '/api/health'
    | '/api/journal'
    | '/api/lang'
    | '/api/units'
    | '/api/unlock'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/setup'
    | '/api/disks/power'
    | '/api/disks/smart'
    | '/api/favicon/$key'
    | '/api/icons/$slug'
    | '/api/icons/search'
    | '/api/jobs/$id'
    | '/api/layout/hidden'
    | '/api/links/$id'
    | '/api/metrics/containers'
    | '/api/metrics/history'
    | '/api/network/devices'
    | '/api/podman/settings'
    | '/api/podman/storage'
    | '/api/quadlets/compose'
    | '/api/quadlets/file'
    | '/api/quadlets/revision'
    | '/api/quadlets/validate'
    | '/api/services/override'
    | '/api/system/config'
    | '/api/system/images'
    | '/api/system/overview'
    | '/api/system/remove-preview'
    | '/api/system/updates'
    | '/api/backup/'
    | '/api/boot/'
    | '/api/caddy/'
    | '/api/files/'
    | '/api/fstab/'
    | '/api/hardware/'
    | '/api/jobs/'
    | '/api/layout/'
    | '/api/links/'
    | '/api/network/'
    | '/api/notifications/'
    | '/api/power/'
    | '/api/quadlets/'
    | '/api/shares/'
    | '/api/speedtest/'
    | '/api/ssh/'
    | '/api/systemd/'
    | '/api/timers/'
    | '/api/users/'
    | '/api/backup/script/$token'
    | '/api/system/packages/$name'
    | '/api/system/packages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/backups'
    | '/disks'
    | '/files'
    | '/hardware'
    | '/journal'
    | '/network'
    | '/notifications'
    | '/quadlets'
    | '/shares'
    | '/ssh'
    | '/system'
    | '/systemd'
    | '/units'
    | '/users'
    | '/api/containers'
    | '/api/events'
    | '/api/health'
    | '/api/journal'
    | '/api/lang'
    | '/api/units'
    | '/api/unlock'
    | '/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/setup'
    | '/api/disks/power'
    | '/api/disks/smart'
    | '/api/favicon/$key'
    | '/api/icons/$slug'
    | '/api/icons/search'
    | '/api/jobs/$id'
    | '/api/layout/hidden'
    | '/api/links/$id'
    | '/api/metrics/containers'
    | '/api/metrics/history'
    | '/api/network/devices'
    | '/api/podman/settings'
    | '/api/podman/storage'
    | '/api/quadlets/compose'
    | '/api/quadlets/file'
    | '/api/quadlets/revision'
    | '/api/quadlets/validate'
    | '/api/services/override'
    | '/api/system/config'
    | '/api/system/images'
    | '/api/system/overview'
    | '/api/system/remove-preview'
    | '/api/system/updates'
    | '/api/backup'
    | '/api/boot'
    | '/api/caddy'
    | '/api/files'
    | '/api/fstab'
    | '/api/hardware'
    | '/api/jobs'
    | '/api/layout'
    | '/api/links'
    | '/api/network'
    | '/api/notifications'
    | '/api/power'
    | '/api/quadlets'
    | '/api/shares'
    | '/api/speedtest'
    | '/api/ssh'
    | '/api/systemd'
    | '/api/timers'
    | '/api/users'
    | '/api/backup/script/$token'
    | '/api/system/packages/$name'
    | '/api/system/packages'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/backups'
    | '/_app/disks'
    | '/_app/files'
    | '/_app/hardware'
    | '/_app/journal'
    | '/_app/network'
    | '/_app/notifications'
    | '/_app/quadlets'
    | '/_app/shares'
    | '/_app/ssh'
    | '/_app/system'
    | '/_app/systemd'
    | '/_app/units'
    | '/_app/users'
    | '/api/containers'
    | '/api/events'
    | '/api/health'
    | '/api/journal'
    | '/api/lang'
    | '/api/units'
    | '/api/unlock'
    | '/_app/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/setup'
    | '/api/disks/power'
    | '/api/disks/smart'
    | '/api/favicon/$key'
    | '/api/icons/$slug'
    | '/api/icons/search'
    | '/api/jobs/$id'
    | '/api/layout/hidden'
    | '/api/links/$id'
    | '/api/metrics/containers'
    | '/api/metrics/history'
    | '/api/network/devices'
    | '/api/podman/settings'
    | '/api/podman/storage'
    | '/api/quadlets/compose'
    | '/api/quadlets/file'
    | '/api/quadlets/revision'
    | '/api/quadlets/validate'
    | '/api/services/override'
    | '/api/system/config'
    | '/api/system/images'
    | '/api/system/overview'
    | '/api/system/remove-preview'
    | '/api/system/updates'
    | '/api/backup/'
    | '/api/boot/'
    | '/api/caddy/'
    | '/api/files/'
    | '/api/fstab/'
    | '/api/hardware/'
    | '/api/jobs/'
    | '/api/layout/'
    | '/api/links/'
    | '/api/network/'
    | '/api/notifications/'
    | '/api/power/'
    | '/api/quadlets/'
    | '/api/shares/'
    | '/api/speedtest/'
    | '/api/ssh/'
    | '/api/systemd/'
    | '/api/timers/'
    | '/api/users/'
    | '/api/backup/script/$token'
    | '/api/system/packages/$name'
    | '/api/system/packages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiContainersRoute: typeof ApiContainersRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiJournalRoute: typeof ApiJournalRoute
  ApiLangRoute: typeof ApiLangRoute
  ApiUnitsRoute: typeof ApiUnitsRoute
  ApiUnlockRoute: typeof ApiUnlockRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSetupRoute: typeof ApiAuthSetupRoute
  ApiDisksPowerRoute: typeof ApiDisksPowerRoute
  ApiDisksSmartRoute: typeof ApiDisksSmartRoute
  ApiFaviconKeyRoute: typeof ApiFaviconKeyRoute
  ApiIconsSlugRoute: typeof ApiIconsSlugRoute
  ApiIconsSearchRoute: typeof ApiIconsSearchRoute
  ApiJobsIdRoute: typeof ApiJobsIdRoute
  ApiLayoutHiddenRoute: typeof ApiLayoutHiddenRoute
  ApiLinksIdRoute: typeof ApiLinksIdRoute
  ApiMetricsContainersRoute: typeof ApiMetricsContainersRoute
  ApiMetricsHistoryRoute: typeof ApiMetricsHistoryRoute
  ApiNetworkDevicesRoute: typeof ApiNetworkDevicesRoute
  ApiPodmanSettingsRoute: typeof ApiPodmanSettingsRoute
  ApiPodmanStorageRoute: typeof ApiPodmanStorageRoute
  ApiQuadletsComposeRoute: typeof ApiQuadletsComposeRoute
  ApiQuadletsFileRoute: typeof ApiQuadletsFileRoute
  ApiQuadletsRevisionRoute: typeof ApiQuadletsRevisionRoute
  ApiQuadletsValidateRoute: typeof ApiQuadletsValidateRoute
  ApiServicesOverrideRoute: typeof ApiServicesOverrideRoute
  ApiSystemConfigRoute: typeof ApiSystemConfigRoute
  ApiSystemImagesRoute: typeof ApiSystemImagesRoute
  ApiSystemOverviewRoute: typeof ApiSystemOverviewRoute
  ApiSystemRemovePreviewRoute: typeof ApiSystemRemovePreviewRoute
  ApiSystemUpdatesRoute: typeof ApiSystemUpdatesRoute
  ApiBackupIndexRoute: typeof ApiBackupIndexRoute
  ApiBootIndexRoute: typeof ApiBootIndexRoute
  ApiCaddyIndexRoute: typeof ApiCaddyIndexRoute
  ApiFilesIndexRoute: typeof ApiFilesIndexRoute
  ApiFstabIndexRoute: typeof ApiFstabIndexRoute
  ApiHardwareIndexRoute: typeof ApiHardwareIndexRoute
  ApiJobsIndexRoute: typeof ApiJobsIndexRoute
  ApiLayoutIndexRoute: typeof ApiLayoutIndexRoute
  ApiLinksIndexRoute: typeof ApiLinksIndexRoute
  ApiNetworkIndexRoute: typeof ApiNetworkIndexRoute
  ApiNotificationsIndexRoute: typeof ApiNotificationsIndexRoute
  ApiPowerIndexRoute: typeof ApiPowerIndexRoute
  ApiQuadletsIndexRoute: typeof ApiQuadletsIndexRoute
  ApiSharesIndexRoute: typeof ApiSharesIndexRoute
  ApiSpeedtestIndexRoute: typeof ApiSpeedtestIndexRoute
  ApiSshIndexRoute: typeof ApiSshIndexRoute
  ApiSystemdIndexRoute: typeof ApiSystemdIndexRoute
  ApiTimersIndexRoute: typeof ApiTimersIndexRoute
  ApiUsersIndexRoute: typeof ApiUsersIndexRoute
  ApiBackupScriptTokenRoute: typeof ApiBackupScriptTokenRoute
  ApiSystemPackagesNameRoute: typeof ApiSystemPackagesNameRoute
  ApiSystemPackagesIndexRoute: typeof ApiSystemPackagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backups': {
      id: '/_app/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AppBackupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disks': {
      id: '/_app/disks'
      path: '/disks'
      fullPath: '/disks'
      preLoaderRoute: typeof AppDisksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/files': {
      id: '/_app/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hardware': {
      id: '/_app/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof AppHardwareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network': {
      id: '/_app/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quadlets': {
      id: '/_app/quadlets'
      path: '/quadlets'
      fullPath: '/quadlets'
      preLoaderRoute: typeof AppQuadletsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shares': {
      id: '/_app/shares'
      path: '/shares'
      fullPath: '/shares'
      preLoaderRoute: typeof AppSharesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ssh': {
      id: '/_app/ssh'
      path: '/ssh'
      fullPath: '/ssh'
      preLoaderRoute: typeof AppSshRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/systemd': {
      id: '/_app/systemd'
      path: '/systemd'
      fullPath: '/systemd'
      preLoaderRoute: typeof AppSystemdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/units': {
      id: '/_app/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AppUnitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/containers': {
      id: '/api/containers'
      path: '/api/containers'
      fullPath: '/api/containers'
      preLoaderRoute: typeof ApiContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/journal': {
      id: '/api/journal'
      path: '/api/journal'
      fullPath: '/api/journal'
      preLoaderRoute: typeof ApiJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lang': {
      id: '/api/lang'
      path: '/api/lang'
      fullPath: '/api/lang'
      preLoaderRoute: typeof ApiLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/units': {
      id: '/api/units'
      path: '/api/units'
      fullPath: '/api/units'
      preLoaderRoute: typeof ApiUnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unlock': {
      id: '/api/unlock'
      path: '/api/unlock'
      fullPath: '/api/unlock'
      preLoaderRoute: typeof ApiUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/setup': {
      id: '/api/auth/setup'
      path: '/api/auth/setup'
      fullPath: '/api/auth/setup'
      preLoaderRoute: typeof ApiAuthSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backup/': {
      id: '/api/backup/'
      path: '/api/backup'
      fullPath: '/api/backup/'
      preLoaderRoute: typeof ApiBackupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boot/': {
      id: '/api/boot/'
      path: '/api/boot'
      fullPath: '/api/boot/'
      preLoaderRoute: typeof ApiBootIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/caddy/': {
      id: '/api/caddy/'
      path: '/api/caddy'
      fullPath: '/api/caddy/'
      preLoaderRoute: typeof ApiCaddyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/disks/power': {
      id: '/api/disks/power'
      path: '/api/disks/power'
      fullPath: '/api/disks/power'
      preLoaderRoute: typeof ApiDisksPowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/disks/smart': {
      id: '/api/disks/smart'
      path: '/api/disks/smart'
      fullPath: '/api/disks/smart'
      preLoaderRoute: typeof ApiDisksSmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/favicon/$key': {
      id: '/api/favicon/$key'
      path: '/api/favicon/$key'
      fullPath: '/api/favicon/$key'
      preLoaderRoute: typeof ApiFaviconKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/': {
      id: '/api/files/'
      path: '/api/files'
      fullPath: '/api/files/'
      preLoaderRoute: typeof ApiFilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fstab/': {
      id: '/api/fstab/'
      path: '/api/fstab'
      fullPath: '/api/fstab/'
      preLoaderRoute: typeof ApiFstabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hardware/': {
      id: '/api/hardware/'
      path: '/api/hardware'
      fullPath: '/api/hardware/'
      preLoaderRoute: typeof ApiHardwareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/icons/$slug': {
      id: '/api/icons/$slug'
      path: '/api/icons/$slug'
      fullPath: '/api/icons/$slug'
      preLoaderRoute: typeof ApiIconsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/icons/search': {
      id: '/api/icons/search'
      path: '/api/icons/search'
      fullPath: '/api/icons/search'
      preLoaderRoute: typeof ApiIconsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/': {
      id: '/api/jobs/'
      path: '/api/jobs'
      fullPath: '/api/jobs/'
      preLoaderRoute: typeof ApiJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id': {
      id: '/api/jobs/$id'
      path: '/api/jobs/$id'
      fullPath: '/api/jobs/$id'
      preLoaderRoute: typeof ApiJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/layout/': {
      id: '/api/layout/'
      path: '/api/layout'
      fullPath: '/api/layout/'
      preLoaderRoute: typeof ApiLayoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/layout/hidden': {
      id: '/api/layout/hidden'
      path: '/api/layout/hidden'
      fullPath: '/api/layout/hidden'
      preLoaderRoute: typeof ApiLayoutHiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/links/': {
      id: '/api/links/'
      path: '/api/links'
      fullPath: '/api/links/'
      preLoaderRoute: typeof ApiLinksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/links/$id': {
      id: '/api/links/$id'
      path: '/api/links/$id'
      fullPath: '/api/links/$id'
      preLoaderRoute: typeof ApiLinksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metrics/containers': {
      id: '/api/metrics/containers'
      path: '/api/metrics/containers'
      fullPath: '/api/metrics/containers'
      preLoaderRoute: typeof ApiMetricsContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metrics/history': {
      id: '/api/metrics/history'
      path: '/api/metrics/history'
      fullPath: '/api/metrics/history'
      preLoaderRoute: typeof ApiMetricsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/network/': {
      id: '/api/network/'
      path: '/api/network'
      fullPath: '/api/network/'
      preLoaderRoute: typeof ApiNetworkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/network/devices': {
      id: '/api/network/devices'
      path: '/api/network/devices'
      fullPath: '/api/network/devices'
      preLoaderRoute: typeof ApiNetworkDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/': {
      id: '/api/notifications/'
      path: '/api/notifications'
      fullPath: '/api/notifications/'
      preLoaderRoute: typeof ApiNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/podman/settings': {
      id: '/api/podman/settings'
      path: '/api/podman/settings'
      fullPath: '/api/podman/settings'
      preLoaderRoute: typeof ApiPodmanSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/podman/storage': {
      id: '/api/podman/storage'
      path: '/api/podman/storage'
      fullPath: '/api/podman/storage'
      preLoaderRoute: typeof ApiPodmanStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/power/': {
      id: '/api/power/'
      path: '/api/power'
      fullPath: '/api/power/'
      preLoaderRoute: typeof ApiPowerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quadlets/': {
      id: '/api/quadlets/'
      path: '/api/quadlets'
      fullPath: '/api/quadlets/'
      preLoaderRoute: typeof ApiQuadletsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quadlets/compose': {
      id: '/api/quadlets/compose'
      path: '/api/quadlets/compose'
      fullPath: '/api/quadlets/compose'
      preLoaderRoute: typeof ApiQuadletsComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quadlets/file': {
      id: '/api/quadlets/file'
      path: '/api/quadlets/file'
      fullPath: '/api/quadlets/file'
      preLoaderRoute: typeof ApiQuadletsFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quadlets/revision': {
      id: '/api/quadlets/revision'
      path: '/api/quadlets/revision'
      fullPath: '/api/quadlets/revision'
      preLoaderRoute: typeof ApiQuadletsRevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quadlets/validate': {
      id: '/api/quadlets/validate'
      path: '/api/quadlets/validate'
      fullPath: '/api/quadlets/validate'
      preLoaderRoute: typeof ApiQuadletsValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/services/override': {
      id: '/api/services/override'
      path: '/api/services/override'
      fullPath: '/api/services/override'
      preLoaderRoute: typeof ApiServicesOverrideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shares/': {
      id: '/api/shares/'
      path: '/api/shares'
      fullPath: '/api/shares/'
      preLoaderRoute: typeof ApiSharesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speedtest/': {
      id: '/api/speedtest/'
      path: '/api/speedtest'
      fullPath: '/api/speedtest/'
      preLoaderRoute: typeof ApiSpeedtestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ssh/': {
      id: '/api/ssh/'
      path: '/api/ssh'
      fullPath: '/api/ssh/'
      preLoaderRoute: typeof ApiSshIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/config': {
      id: '/api/system/config'
      path: '/api/system/config'
      fullPath: '/api/system/config'
      preLoaderRoute: typeof ApiSystemConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/images': {
      id: '/api/system/images'
      path: '/api/system/images'
      fullPath: '/api/system/images'
      preLoaderRoute: typeof ApiSystemImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/overview': {
      id: '/api/system/overview'
      path: '/api/system/overview'
      fullPath: '/api/system/overview'
      preLoaderRoute: typeof ApiSystemOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/remove-preview': {
      id: '/api/system/remove-preview'
      path: '/api/system/remove-preview'
      fullPath: '/api/system/remove-preview'
      preLoaderRoute: typeof ApiSystemRemovePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/updates': {
      id: '/api/system/updates'
      path: '/api/system/updates'
      fullPath: '/api/system/updates'
      preLoaderRoute: typeof ApiSystemUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/systemd/': {
      id: '/api/systemd/'
      path: '/api/systemd'
      fullPath: '/api/systemd/'
      preLoaderRoute: typeof ApiSystemdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/timers/': {
      id: '/api/timers/'
      path: '/api/timers'
      fullPath: '/api/timers/'
      preLoaderRoute: typeof ApiTimersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/': {
      id: '/api/users/'
      path: '/api/users'
      fullPath: '/api/users/'
      preLoaderRoute: typeof ApiUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backup/script/$token': {
      id: '/api/backup/script/$token'
      path: '/api/backup/script/$token'
      fullPath: '/api/backup/script/$token'
      preLoaderRoute: typeof ApiBackupScriptTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/packages/': {
      id: '/api/system/packages/'
      path: '/api/system/packages'
      fullPath: '/api/system/packages/'
      preLoaderRoute: typeof ApiSystemPackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/packages/$name': {
      id: '/api/system/packages/$name'
      path: '/api/system/packages/$name'
      fullPath: '/api/system/packages/$name'
      preLoaderRoute: typeof ApiSystemPackagesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBackupsRoute: typeof AppBackupsRoute
  AppDisksRoute: typeof AppDisksRoute
  AppFilesRoute: typeof AppFilesRoute
  AppHardwareRoute: typeof AppHardwareRoute
  AppJournalRoute: typeof AppJournalRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppQuadletsRoute: typeof AppQuadletsRoute
  AppSharesRoute: typeof AppSharesRoute
  AppSshRoute: typeof AppSshRoute
  AppSystemRoute: typeof AppSystemRoute
  AppSystemdRoute: typeof AppSystemdRoute
  AppUnitsRoute: typeof AppUnitsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBackupsRoute: AppBackupsRoute,
  AppDisksRoute: AppDisksRoute,
  AppFilesRoute: AppFilesRoute,
  AppHardwareRoute: AppHardwareRoute,
  AppJournalRoute: AppJournalRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppQuadletsRoute: AppQuadletsRoute,
  AppSharesRoute: AppSharesRoute,
  AppSshRoute: AppSshRoute,
  AppSystemRoute: AppSystemRoute,
  AppSystemdRoute: AppSystemdRoute,
  AppUnitsRoute: AppUnitsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiContainersRoute: ApiContainersRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiJournalRoute: ApiJournalRoute,
  ApiLangRoute: ApiLangRoute,
  ApiUnitsRoute: ApiUnitsRoute,
  ApiUnlockRoute: ApiUnlockRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSetupRoute: ApiAuthSetupRoute,
  ApiDisksPowerRoute: ApiDisksPowerRoute,
  ApiDisksSmartRoute: ApiDisksSmartRoute,
  ApiFaviconKeyRoute: ApiFaviconKeyRoute,
  ApiIconsSlugRoute: ApiIconsSlugRoute,
  ApiIconsSearchRoute: ApiIconsSearchRoute,
  ApiJobsIdRoute: ApiJobsIdRoute,
  ApiLayoutHiddenRoute: ApiLayoutHiddenRoute,
  ApiLinksIdRoute: ApiLinksIdRoute,
  ApiMetricsContainersRoute: ApiMetricsContainersRoute,
  ApiMetricsHistoryRoute: ApiMetricsHistoryRoute,
  ApiNetworkDevicesRoute: ApiNetworkDevicesRoute,
  ApiPodmanSettingsRoute: ApiPodmanSettingsRoute,
  ApiPodmanStorageRoute: ApiPodmanStorageRoute,
  ApiQuadletsComposeRoute: ApiQuadletsComposeRoute,
  ApiQuadletsFileRoute: ApiQuadletsFileRoute,
  ApiQuadletsRevisionRoute: ApiQuadletsRevisionRoute,
  ApiQuadletsValidateRoute: ApiQuadletsValidateRoute,
  ApiServicesOverrideRoute: ApiServicesOverrideRoute,
  ApiSystemConfigRoute: ApiSystemConfigRoute,
  ApiSystemImagesRoute: ApiSystemImagesRoute,
  ApiSystemOverviewRoute: ApiSystemOverviewRoute,
  ApiSystemRemovePreviewRoute: ApiSystemRemovePreviewRoute,
  ApiSystemUpdatesRoute: ApiSystemUpdatesRoute,
  ApiBackupIndexRoute: ApiBackupIndexRoute,
  ApiBootIndexRoute: ApiBootIndexRoute,
  ApiCaddyIndexRoute: ApiCaddyIndexRoute,
  ApiFilesIndexRoute: ApiFilesIndexRoute,
  ApiFstabIndexRoute: ApiFstabIndexRoute,
  ApiHardwareIndexRoute: ApiHardwareIndexRoute,
  ApiJobsIndexRoute: ApiJobsIndexRoute,
  ApiLayoutIndexRoute: ApiLayoutIndexRoute,
  ApiLinksIndexRoute: ApiLinksIndexRoute,
  ApiNetworkIndexRoute: ApiNetworkIndexRoute,
  ApiNotificationsIndexRoute: ApiNotificationsIndexRoute,
  ApiPowerIndexRoute: ApiPowerIndexRoute,
  ApiQuadletsIndexRoute: ApiQuadletsIndexRoute,
  ApiSharesIndexRoute: ApiSharesIndexRoute,
  ApiSpeedtestIndexRoute: ApiSpeedtestIndexRoute,
  ApiSshIndexRoute: ApiSshIndexRoute,
  ApiSystemdIndexRoute: ApiSystemdIndexRoute,
  ApiTimersIndexRoute: ApiTimersIndexRoute,
  ApiUsersIndexRoute: ApiUsersIndexRoute,
  ApiBackupScriptTokenRoute: ApiBackupScriptTokenRoute,
  ApiSystemPackagesNameRoute: ApiSystemPackagesNameRoute,
  ApiSystemPackagesIndexRoute: ApiSystemPackagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
